// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Surveys.Item.Activity;
using Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Surveys.Item.ArchivedResponseUuids;
using Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Surveys.Item.Duplicate_to_projects;
using Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Surveys.Item.Responses;
using Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Surveys.Item.Stats;
using Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Surveys.Item.Summarize_responses;
using Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Surveys.Item.Summary_headline;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Surveys.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\projects\{project_id}\surveys\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SurveysItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The activity property</summary>
        public global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Surveys.Item.Activity.ActivityRequestBuilder Activity
        {
            get => new global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Surveys.Item.Activity.ActivityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The archivedResponseUuids property</summary>
        public global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Surveys.Item.ArchivedResponseUuids.ArchivedResponseUuidsRequestBuilder ArchivedResponseUuids
        {
            get => new global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Surveys.Item.ArchivedResponseUuids.ArchivedResponseUuidsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The duplicate_to_projects property</summary>
        public global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Surveys.Item.Duplicate_to_projects.Duplicate_to_projectsRequestBuilder Duplicate_to_projects
        {
            get => new global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Surveys.Item.Duplicate_to_projects.Duplicate_to_projectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The EmptyPathSegment property</summary>
        public global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Surveys.Item.EmptyPathSegmentRequestBuilder EmptyPathSegment
        {
            get => new global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Surveys.Item.EmptyPathSegmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The responses property</summary>
        public global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Surveys.Item.Responses.ResponsesRequestBuilder Responses
        {
            get => new global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Surveys.Item.Responses.ResponsesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stats property</summary>
        public global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Surveys.Item.Stats.StatsRequestBuilder Stats
        {
            get => new global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Surveys.Item.Stats.StatsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The summarize_responses property</summary>
        public global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Surveys.Item.Summarize_responses.Summarize_responsesRequestBuilder Summarize_responses
        {
            get => new global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Surveys.Item.Summarize_responses.Summarize_responsesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The summary_headline property</summary>
        public global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Surveys.Item.Summary_headline.Summary_headlineRequestBuilder Summary_headline
        {
            get => new global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Surveys.Item.Summary_headline.Summary_headlineRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Surveys.Item.SurveysItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SurveysItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/projects/{project_id}/surveys/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Surveys.Item.SurveysItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SurveysItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/projects/{project_id}/surveys/{id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
