// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.PostHog.OpenApiClient.Api.Users.Item.Integrations.Github.Item.Repos.Refresh;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.PostHog.OpenApiClient.Api.Users.Item.Integrations.Github.Item.Repos
{
    /// <summary>
    /// Builds and executes requests for operations under \api\users\{user_-id}\integrations\github\{installation_id}\repos
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReposRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The EmptyPathSegment property</summary>
        public global::Soenneker.PostHog.OpenApiClient.Api.Users.Item.Integrations.Github.Item.Repos.EmptyPathSegmentRequestBuilder EmptyPathSegment
        {
            get => new global::Soenneker.PostHog.OpenApiClient.Api.Users.Item.Integrations.Github.Item.Repos.EmptyPathSegmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The refresh property</summary>
        public global::Soenneker.PostHog.OpenApiClient.Api.Users.Item.Integrations.Github.Item.Repos.Refresh.RefreshRequestBuilder Refresh
        {
            get => new global::Soenneker.PostHog.OpenApiClient.Api.Users.Item.Integrations.Github.Item.Repos.Refresh.RefreshRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Api.Users.Item.Integrations.Github.Item.Repos.ReposRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReposRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/users/{user_%2Did}/integrations/github/{installation_id}/repos", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Api.Users.Item.Integrations.Github.Item.Repos.ReposRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReposRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/users/{user_%2Did}/integrations/github/{installation_id}/repos", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
