// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Desktop.Access;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Desktop
{
    /// <summary>
    /// Builds and executes requests for operations under \api\projects\{projectId}\desktop
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DesktopRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The access property</summary>
        public global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Desktop.Access.AccessRequestBuilder Access
        {
            get => new global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Desktop.Access.AccessRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Desktop.DesktopRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DesktopRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/projects/{projectId}/desktop", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Desktop.DesktopRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DesktopRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/projects/{projectId}/desktop", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
