// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.PostHog.OpenApiClient.Api.User_facet_settings.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.PostHog.OpenApiClient.Api.User_facet_settings
{
    /// <summary>
    /// Builds and executes requests for operations under \api\user_facet_settings
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class User_facet_settingsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.PostHog.OpenApiClient.api.user_facet_settings.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Api.User_facet_settings.Item.WithUuItemRequestBuilder"/></returns>
        public global::Soenneker.PostHog.OpenApiClient.Api.User_facet_settings.Item.WithUuItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("uuid", position);
                return new global::Soenneker.PostHog.OpenApiClient.Api.User_facet_settings.Item.WithUuItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Api.User_facet_settings.User_facet_settingsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public User_facet_settingsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/user_facet_settings", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Api.User_facet_settings.User_facet_settingsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public User_facet_settingsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/user_facet_settings", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
