// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Data_catalog.Relationship_proposals.Item;
using Soenneker.PostHog.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Data_catalog.Relationship_proposals
{
    /// <summary>
    /// Builds and executes requests for operations under \api\projects\{projectId}\data_catalog\relationship_proposals
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Relationship_proposalsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.PostHog.OpenApiClient.api.projects.item.data_catalog.relationship_proposals.item collection</summary>
        /// <param name="position">A UUID string identifying this relationship proposal.</param>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Data_catalog.Relationship_proposals.Item.Relationship_proposalsItemRequestBuilder"/></returns>
        public global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Data_catalog.Relationship_proposals.Item.Relationship_proposalsItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Data_catalog.Relationship_proposals.Item.Relationship_proposalsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Data_catalog.Relationship_proposals.Relationship_proposalsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Relationship_proposalsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/projects/{projectId}/data_catalog/relationship_proposals{?limit*,offset*,status*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Data_catalog.Relationship_proposals.Relationship_proposalsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Relationship_proposalsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/projects/{projectId}/data_catalog/relationship_proposals{?limit*,offset*,status*}", rawUrl)
        {
        }
        /// <summary>
        /// Reviewed join facts. Accepting one promotes it to a real DataWarehouseJoin; rejections persist.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.PaginatedDataCatalogRelationshipProposalList"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.PostHog.OpenApiClient.Models.PaginatedDataCatalogRelationshipProposalList?> GetAsync(Action<RequestConfiguration<global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Data_catalog.Relationship_proposals.Relationship_proposalsRequestBuilder.Relationship_proposalsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.PostHog.OpenApiClient.Models.PaginatedDataCatalogRelationshipProposalList> GetAsync(Action<RequestConfiguration<global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Data_catalog.Relationship_proposals.Relationship_proposalsRequestBuilder.Relationship_proposalsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.PostHog.OpenApiClient.Models.PaginatedDataCatalogRelationshipProposalList>(requestInfo, global::Soenneker.PostHog.OpenApiClient.Models.PaginatedDataCatalogRelationshipProposalList.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Reviewed join facts. Accepting one promotes it to a real DataWarehouseJoin; rejections persist.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.DataCatalogRelationshipProposal"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.PostHog.OpenApiClient.Models.DataCatalogRelationshipProposal?> PostAsync(global::Soenneker.PostHog.OpenApiClient.Models.DataCatalogRelationshipProposal body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.PostHog.OpenApiClient.Models.DataCatalogRelationshipProposal> PostAsync(global::Soenneker.PostHog.OpenApiClient.Models.DataCatalogRelationshipProposal body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.PostHog.OpenApiClient.Models.DataCatalogRelationshipProposal>(requestInfo, global::Soenneker.PostHog.OpenApiClient.Models.DataCatalogRelationshipProposal.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Reviewed join facts. Accepting one promotes it to a real DataWarehouseJoin; rejections persist.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Data_catalog.Relationship_proposals.Relationship_proposalsRequestBuilder.Relationship_proposalsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Data_catalog.Relationship_proposals.Relationship_proposalsRequestBuilder.Relationship_proposalsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Reviewed join facts. Accepting one promotes it to a real DataWarehouseJoin; rejections persist.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.PostHog.OpenApiClient.Models.DataCatalogRelationshipProposal body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.PostHog.OpenApiClient.Models.DataCatalogRelationshipProposal body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Data_catalog.Relationship_proposals.Relationship_proposalsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Data_catalog.Relationship_proposals.Relationship_proposalsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Data_catalog.Relationship_proposals.Relationship_proposalsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Reviewed join facts. Accepting one promotes it to a real DataWarehouseJoin; rejections persist.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Relationship_proposalsRequestBuilderGetQueryParameters 
        {
            /// <summary>Number of results to return per page.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>The initial index from which to return the results.</summary>
            [QueryParameter("offset")]
            public int? Offset { get; set; }
            /// <summary>Filter by proposed/accepted/rejected.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("status")]
            public string? Status { get; set; }
#nullable restore
#else
            [QueryParameter("status")]
            public string Status { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
