// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.PostHog.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Engineering_analytics.Team_ci_health
{
    /// <summary>
    /// Builds and executes requests for operations under \api\projects\{projectId}\engineering_analytics\team_ci_health
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Team_ci_healthRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Engineering_analytics.Team_ci_health.Team_ci_healthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Team_ci_healthRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/projects/{projectId}/engineering_analytics/team_ci_health{?date_from*,date_to*,limit*,min_failed_prs*,source_id*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Engineering_analytics.Team_ci_health.Team_ci_healthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Team_ci_healthRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/projects/{projectId}/engineering_analytics/team_ci_health{?date_from*,date_to*,limit*,min_failed_prs*,source_id*}", rawUrl)
        {
        }
        /// <summary>
        /// &quot;Per-owning-team rollup of the CI test surfaces each team owns, over the same run evidence as flaky_tests and with the same meaning of flaky: flaky_test_count is owned tests one commit was seen both failing and passing in the window, regression_test_count is owned tests that failed with no such proof and still hit the blast-radius bar, plus failed/recovery/quarantined run counts. Each has an equal-length previous-window twin for honest deltas. Ownership is stamped on the spans at CI emission time from the repo&apos;s ownership map (products/*/product.yaml + CODEOWNERS); unstamped spans aggregate under the literal team &apos;unowned&apos;, and a re-stamped test lands under its latest owner only. Teams are organizational owners of code surfaces, never authors. Counts are absolute, never rates: CI emits every failure but omits ordinary passing spans, so there is no execution denominator. &apos;suspected_regression&apos; means no recovery was recorded in this data, not that the test never flakes.&quot;
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.TeamCiHealthList"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.PostHog.OpenApiClient.Models.TeamCiHealthList?> GetAsync(Action<RequestConfiguration<global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Engineering_analytics.Team_ci_health.Team_ci_healthRequestBuilder.Team_ci_healthRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.PostHog.OpenApiClient.Models.TeamCiHealthList> GetAsync(Action<RequestConfiguration<global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Engineering_analytics.Team_ci_health.Team_ci_healthRequestBuilder.Team_ci_healthRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.PostHog.OpenApiClient.Models.TeamCiHealthList>(requestInfo, global::Soenneker.PostHog.OpenApiClient.Models.TeamCiHealthList.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &quot;Per-owning-team rollup of the CI test surfaces each team owns, over the same run evidence as flaky_tests and with the same meaning of flaky: flaky_test_count is owned tests one commit was seen both failing and passing in the window, regression_test_count is owned tests that failed with no such proof and still hit the blast-radius bar, plus failed/recovery/quarantined run counts. Each has an equal-length previous-window twin for honest deltas. Ownership is stamped on the spans at CI emission time from the repo&apos;s ownership map (products/*/product.yaml + CODEOWNERS); unstamped spans aggregate under the literal team &apos;unowned&apos;, and a re-stamped test lands under its latest owner only. Teams are organizational owners of code surfaces, never authors. Counts are absolute, never rates: CI emits every failure but omits ordinary passing spans, so there is no execution denominator. &apos;suspected_regression&apos; means no recovery was recorded in this data, not that the test never flakes.&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Engineering_analytics.Team_ci_health.Team_ci_healthRequestBuilder.Team_ci_healthRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Engineering_analytics.Team_ci_health.Team_ci_healthRequestBuilder.Team_ci_healthRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Engineering_analytics.Team_ci_health.Team_ci_healthRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Engineering_analytics.Team_ci_health.Team_ci_healthRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Engineering_analytics.Team_ci_health.Team_ci_healthRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &quot;Per-owning-team rollup of the CI test surfaces each team owns, over the same run evidence as flaky_tests and with the same meaning of flaky: flaky_test_count is owned tests one commit was seen both failing and passing in the window, regression_test_count is owned tests that failed with no such proof and still hit the blast-radius bar, plus failed/recovery/quarantined run counts. Each has an equal-length previous-window twin for honest deltas. Ownership is stamped on the spans at CI emission time from the repo&apos;s ownership map (products/*/product.yaml + CODEOWNERS); unstamped spans aggregate under the literal team &apos;unowned&apos;, and a re-stamped test lands under its latest owner only. Teams are organizational owners of code surfaces, never authors. Counts are absolute, never rates: CI emits every failure but omits ordinary passing spans, so there is no execution denominator. &apos;suspected_regression&apos; means no recovery was recorded in this data, not that the test never flakes.&quot;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Team_ci_healthRequestBuilderGetQueryParameters 
        {
            /// <summary>&quot;Window start: relative (&apos;-14d&apos;, &apos;-7d&apos;) or ISO8601. Defaults to -14d; the window may span at most 30 days. An equal-length prior window is scanned for the *_prior twins; near the 30-day ceiling that prior window can reach past Traces retention, deflating *_prior counts and overstating deltas.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("date_from")]
            public string? DateFrom { get; set; }
#nullable restore
#else
            [QueryParameter("date_from")]
            public string DateFrom { get; set; }
#endif
            /// <summary>&quot;Window end: relative or ISO8601. Defaults to now.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("date_to")]
            public string? DateTo { get; set; }
#nullable restore
#else
            [QueryParameter("date_to")]
            public string DateTo { get; set; }
#endif
            /// <summary>Maximum number of teams to return (1-200). Defaults to 100.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>An unrecovered test counts toward regression_test_count once it failed on at least this many distinct pull requests in the window. Minimum 1. Defaults to 3. Does not affect flaky_test_count, which needs proof, not a threshold.</summary>
            [QueryParameter("min_failed_prs")]
            public int? MinFailedPrs { get; set; }
            /// <summary>Connected GitHub data warehouse source to read from. Defaults to the oldest connected GitHub source when the team has more than one.</summary>
            [QueryParameter("source_id")]
            public Guid? SourceId { get; set; }
        }
    }
}
#pragma warning restore CS0618
