// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ActorsPropertyTaxonomyQuery : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The groupTypeIndex property</summary>
        public int? GroupTypeIndex { get; set; }
        /// <summary>The kind property</summary>
        public global::Soenneker.PostHog.OpenApiClient.Models.ActorsPropertyTaxonomyQuery_kind? Kind { get; set; }
        /// <summary>The maxPropertyValues property</summary>
        public int? MaxPropertyValues { get; set; }
        /// <summary>The modifiers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.HogQLQueryModifiers? Modifiers { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.HogQLQueryModifiers Modifiers { get; set; }
#endif
        /// <summary>The properties property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Properties { get; set; }
#nullable restore
#else
        public List<string> Properties { get; set; }
#endif
        /// <summary>The response property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.ActorsPropertyTaxonomyQueryResponse? Response { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.ActorsPropertyTaxonomyQueryResponse Response { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.QueryLogTags? Tags { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.QueryLogTags Tags { get; set; }
#endif
        /// <summary>version of the node, used for schema migrations</summary>
        public double? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Models.ActorsPropertyTaxonomyQuery"/> and sets the default values.
        /// </summary>
        public ActorsPropertyTaxonomyQuery()
        {
            Kind = global::Soenneker.PostHog.OpenApiClient.Models.ActorsPropertyTaxonomyQuery_kind.ActorsPropertyTaxonomyQuery;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.ActorsPropertyTaxonomyQuery"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PostHog.OpenApiClient.Models.ActorsPropertyTaxonomyQuery CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PostHog.OpenApiClient.Models.ActorsPropertyTaxonomyQuery();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "groupTypeIndex", n => { GroupTypeIndex = n.GetIntValue(); } },
                { "kind", n => { Kind = n.GetEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.ActorsPropertyTaxonomyQuery_kind>(); } },
                { "maxPropertyValues", n => { MaxPropertyValues = n.GetIntValue(); } },
                { "modifiers", n => { Modifiers = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.HogQLQueryModifiers>(global::Soenneker.PostHog.OpenApiClient.Models.HogQLQueryModifiers.CreateFromDiscriminatorValue); } },
                { "properties", n => { Properties = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "response", n => { Response = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.ActorsPropertyTaxonomyQueryResponse>(global::Soenneker.PostHog.OpenApiClient.Models.ActorsPropertyTaxonomyQueryResponse.CreateFromDiscriminatorValue); } },
                { "tags", n => { Tags = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.QueryLogTags>(global::Soenneker.PostHog.OpenApiClient.Models.QueryLogTags.CreateFromDiscriminatorValue); } },
                { "version", n => { Version = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("groupTypeIndex", GroupTypeIndex);
            writer.WriteEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.ActorsPropertyTaxonomyQuery_kind>("kind", Kind);
            writer.WriteIntValue("maxPropertyValues", MaxPropertyValues);
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.HogQLQueryModifiers>("modifiers", Modifiers);
            writer.WriteCollectionOfPrimitiveValues<string>("properties", Properties);
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.ActorsPropertyTaxonomyQueryResponse>("response", Response);
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.QueryLogTags>("tags", Tags);
            writer.WriteDoubleValue("version", Version);
        }
    }
}
#pragma warning restore CS0618
