// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BatchExportBackfill : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The actual start time after adjustment for earliest available data. May differ from start_at if user requested a date before data exists.</summary>
        public DateTimeOffset? AdjustedStartAt { get; set; }
        /// <summary>The BatchExport this backfill belongs to.</summary>
        public Guid? BatchExport { get; set; }
        /// <summary>The timestamp at which this BatchExportBackfill was created.</summary>
        public DateTimeOffset? CreatedAt { get; private set; }
        /// <summary>The end of the data interval.</summary>
        public DateTimeOffset? EndAt { get; set; }
        /// <summary>The timestamp at which this BatchExportBackfill finished, successfully or not.</summary>
        public DateTimeOffset? FinishedAt { get; set; }
        /// <summary>The id property</summary>
        public Guid? Id { get; private set; }
        /// <summary>The timestamp at which this BatchExportBackfill was last updated.</summary>
        public DateTimeOffset? LastUpdatedAt { get; private set; }
        /// <summary>The progress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.BatchExportBackfill_progress? Progress { get; private set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.BatchExportBackfill_progress Progress { get; private set; }
#endif
        /// <summary>The start of the data interval.</summary>
        public DateTimeOffset? StartAt { get; set; }
        /// <summary>The status of this backfill.* `Cancelled` - Cancelled* `Completed` - Completed* `ContinuedAsNew` - Continued As New* `Failed` - Failed* `FailedRetryable` - Failed Retryable* `Terminated` - Terminated* `TimedOut` - Timedout* `Running` - Running* `Starting` - Starting</summary>
        public global::Soenneker.PostHog.OpenApiClient.Models.BatchExportBackfillStatusEnum? Status { get; set; }
        /// <summary>The team this belongs to.</summary>
        public int? Team { get; set; }
        /// <summary>The total number of records to export. Initially estimated, updated with actual count after completion.</summary>
        public long? TotalRecordsCount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Models.BatchExportBackfill"/> and sets the default values.
        /// </summary>
        public BatchExportBackfill()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.BatchExportBackfill"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PostHog.OpenApiClient.Models.BatchExportBackfill CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PostHog.OpenApiClient.Models.BatchExportBackfill();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "adjusted_start_at", n => { AdjustedStartAt = n.GetDateTimeOffsetValue(); } },
                { "batch_export", n => { BatchExport = n.GetGuidValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "end_at", n => { EndAt = n.GetDateTimeOffsetValue(); } },
                { "finished_at", n => { FinishedAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "last_updated_at", n => { LastUpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "progress", n => { Progress = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.BatchExportBackfill_progress>(global::Soenneker.PostHog.OpenApiClient.Models.BatchExportBackfill_progress.CreateFromDiscriminatorValue); } },
                { "start_at", n => { StartAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.BatchExportBackfillStatusEnum>(); } },
                { "team", n => { Team = n.GetIntValue(); } },
                { "total_records_count", n => { TotalRecordsCount = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("adjusted_start_at", AdjustedStartAt);
            writer.WriteGuidValue("batch_export", BatchExport);
            writer.WriteDateTimeOffsetValue("end_at", EndAt);
            writer.WriteDateTimeOffsetValue("finished_at", FinishedAt);
            writer.WriteDateTimeOffsetValue("start_at", StartAt);
            writer.WriteEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.BatchExportBackfillStatusEnum>("status", Status);
            writer.WriteIntValue("team", Team);
            writer.WriteLongValue("total_records_count", TotalRecordsCount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
