// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BriefingItemMetric : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>What the value measures, for example affected_users.* `affected_users` - affected_users* `affected_sessions` - affected_sessions* `occurrences` - occurrences* `conversion_rate` - conversion_rate* `error_rate` - error_rate* `duration` - duration* `revenue` - revenue* `custom` - custom</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.BriefingItemMetricKind? Kind { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.BriefingItemMetricKind Kind { get; set; }
#endif
        /// <summary>Stable slug of the metric within its report.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MetricId { get; set; }
#nullable restore
#else
        public string MetricId { get; set; }
#endif
        /// <summary>The metric&apos;s live InsightVizNode wrapping one TrendsQuery, as the report stores it.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.BriefingItemMetricQuery? Query { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.BriefingItemMetricQuery Query { get; set; }
#endif
        /// <summary>`primary` for the report&apos;s key observation, otherwise `supporting`.* `primary` - primary* `supporting` - supporting</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.BriefingItemMetricRole? Role { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.BriefingItemMetricRole Role { get; set; }
#endif
        /// <summary>Trailing per-bucket values saved with the snapshot, oldest first. Null when none were saved.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<double?>? Series { get; set; }
#nullable restore
#else
        public List<double?> Series { get; set; }
#endif
        /// <summary>Short label of what the metric measures.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>Optional short suffix or currency code, such as USD.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Unit { get; set; }
#nullable restore
#else
        public string Unit { get; set; }
#endif
        /// <summary>The latest saved snapshot of the metric.</summary>
        public double? Value { get; set; }
        /// <summary>How to format the value, for example count.* `number` - number* `count` - count* `percentage` - percentage* `percentage_scaled` - percentage_scaled* `duration` - duration* `currency` - currency</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.BriefingItemMetricValueFormat? ValueFormat { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.BriefingItemMetricValueFormat ValueFormat { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Models.BriefingItemMetric"/> and sets the default values.
        /// </summary>
        public BriefingItemMetric()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.BriefingItemMetric"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PostHog.OpenApiClient.Models.BriefingItemMetric CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PostHog.OpenApiClient.Models.BriefingItemMetric();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "kind", n => { Kind = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.BriefingItemMetricKind>(global::Soenneker.PostHog.OpenApiClient.Models.BriefingItemMetricKind.CreateFromDiscriminatorValue); } },
                { "metric_id", n => { MetricId = n.GetStringValue(); } },
                { "query", n => { Query = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.BriefingItemMetricQuery>(global::Soenneker.PostHog.OpenApiClient.Models.BriefingItemMetricQuery.CreateFromDiscriminatorValue); } },
                { "role", n => { Role = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.BriefingItemMetricRole>(global::Soenneker.PostHog.OpenApiClient.Models.BriefingItemMetricRole.CreateFromDiscriminatorValue); } },
                { "series", n => { Series = n.GetCollectionOfPrimitiveValues<double?>()?.AsList(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "unit", n => { Unit = n.GetStringValue(); } },
                { "value", n => { Value = n.GetDoubleValue(); } },
                { "value_format", n => { ValueFormat = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.BriefingItemMetricValueFormat>(global::Soenneker.PostHog.OpenApiClient.Models.BriefingItemMetricValueFormat.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.BriefingItemMetricKind>("kind", Kind);
            writer.WriteStringValue("metric_id", MetricId);
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.BriefingItemMetricQuery>("query", Query);
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.BriefingItemMetricRole>("role", Role);
            writer.WriteCollectionOfPrimitiveValues<double?>("series", Series);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("unit", Unit);
            writer.WriteDoubleValue("value", Value);
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.BriefingItemMetricValueFormat>("value_format", ValueFormat);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
