// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    /// <summary>
    /// Grid-size contract for placements of this component.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CanvasComponentMetaSize : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Height a new placement starts at, in grid rows.</summary>
        public int? DefaultH { get; set; }
        /// <summary>Width a new placement starts at, in grid columns.</summary>
        public int? DefaultW { get; set; }
        /// <summary>Tallest allowed height; omit for no cap.</summary>
        public int? MaxH { get; set; }
        /// <summary>Widest allowed width; omit for no cap below the grid&apos;s width.</summary>
        public int? MaxW { get; set; }
        /// <summary>Shortest height the component renders usefully at.</summary>
        public int? MinH { get; set; }
        /// <summary>Narrowest width the component renders usefully at.</summary>
        public int? MinW { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Models.CanvasComponentMetaSize"/> and sets the default values.
        /// </summary>
        public CanvasComponentMetaSize()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.CanvasComponentMetaSize"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PostHog.OpenApiClient.Models.CanvasComponentMetaSize CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PostHog.OpenApiClient.Models.CanvasComponentMetaSize();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "defaultH", n => { DefaultH = n.GetIntValue(); } },
                { "defaultW", n => { DefaultW = n.GetIntValue(); } },
                { "maxH", n => { MaxH = n.GetIntValue(); } },
                { "maxW", n => { MaxW = n.GetIntValue(); } },
                { "minH", n => { MinH = n.GetIntValue(); } },
                { "minW", n => { MinW = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("defaultH", DefaultH);
            writer.WriteIntValue("defaultW", DefaultW);
            writer.WriteIntValue("maxH", MaxH);
            writer.WriteIntValue("maxW", MaxW);
            writer.WriteIntValue("minH", MinH);
            writer.WriteIntValue("minW", MinW);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
