// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    /// <summary>* `github_actions` - GitHub Actions* `depot_ci` - Depot CI</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CiEngineEnum
    {
        [EnumMember(Value = "github_actions")]
        #pragma warning disable CS1591
        GithubActions,
        #pragma warning restore CS1591
        [EnumMember(Value = "depot_ci")]
        #pragma warning disable CS1591
        DepotCi,
        #pragma warning restore CS1591
    }
}
