// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    /// <summary>* `csv` - csv* `json` - json* `parquet` - parquet</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateTableFromUploadFileFormatEnum
    {
        [EnumMember(Value = "csv")]
        #pragma warning disable CS1591
        Csv,
        #pragma warning restore CS1591
        [EnumMember(Value = "json")]
        #pragma warning disable CS1591
        Json,
        #pragma warning restore CS1591
        [EnumMember(Value = "parquet")]
        #pragma warning disable CS1591
        Parquet,
        #pragma warning restore CS1591
    }
}
