// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    /// <summary>
    /// Lightweight serializer for list views - excludes large query field to reduce memory usage.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DataWarehouseSavedQueryMinimal : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The columns property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PostHog.OpenApiClient.Models.DataWarehouseSavedQueryMinimal_columns>? Columns { get; private set; }
#nullable restore
#else
        public List<global::Soenneker.PostHog.OpenApiClient.Models.DataWarehouseSavedQueryMinimal_columns> Columns { get; private set; }
#endif
        /// <summary>The created_at property</summary>
        public DateTimeOffset? CreatedAt { get; private set; }
        /// <summary>The created_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.UserBasic? CreatedBy { get; private set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.UserBasic CreatedBy { get; private set; }
#endif
        /// <summary>The deleted property</summary>
        public bool? Deleted { get; private set; }
        /// <summary>When this test view should be automatically deleted.</summary>
        public DateTimeOffset? ExpiresAt { get; private set; }
        /// <summary>The folder_id property</summary>
        public Guid? FolderId { get; private set; }
        /// <summary>The folder_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FolderName { get; private set; }
#nullable restore
#else
        public string FolderName { get; private set; }
#endif
        /// <summary>The id property</summary>
        public Guid? Id { get; private set; }
        /// <summary>The is_materialized property</summary>
        public bool? IsMaterialized { get; private set; }
        /// <summary>Whether this view is for testing only and will auto-expire.</summary>
        public bool? IsTest { get; private set; }
        /// <summary>The last_run_at property</summary>
        public DateTimeOffset? LastRunAt { get; private set; }
        /// <summary>The latest_error property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LatestError { get; private set; }
#nullable restore
#else
        public string LatestError { get; private set; }
#endif
        /// <summary>The managed_viewset_kind property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ManagedViewsetKind { get; private set; }
#nullable restore
#else
        public string ManagedViewsetKind { get; private set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; private set; }
#nullable restore
#else
        public string Name { get; private set; }
#endif
        /// <summary>Where this SavedQuery is created.* `data_warehouse` - Data Warehouse* `endpoint` - Endpoint* `managed_viewset` - Managed Viewset</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.DataWarehouseSavedQueryMinimal.DataWarehouseSavedQueryMinimal_origin? Origin { get; private set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.DataWarehouseSavedQueryMinimal.DataWarehouseSavedQueryMinimal_origin Origin { get; private set; }
#endif
        /// <summary>The status of when this SavedQuery last ran.* `Cancelled` - Cancelled* `Modified` - Modified* `Completed` - Completed* `Failed` - Failed* `Running` - Running</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.DataWarehouseSavedQueryMinimal.DataWarehouseSavedQueryMinimal_status? Status { get; private set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.DataWarehouseSavedQueryMinimal.DataWarehouseSavedQueryMinimal_status Status { get; private set; }
#endif
        /// <summary>The sync_frequency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SyncFrequency { get; private set; }
#nullable restore
#else
        public string SyncFrequency { get; private set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Models.DataWarehouseSavedQueryMinimal"/> and sets the default values.
        /// </summary>
        public DataWarehouseSavedQueryMinimal()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.DataWarehouseSavedQueryMinimal"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PostHog.OpenApiClient.Models.DataWarehouseSavedQueryMinimal CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PostHog.OpenApiClient.Models.DataWarehouseSavedQueryMinimal();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "columns", n => { Columns = n.GetCollectionOfObjectValues<global::Soenneker.PostHog.OpenApiClient.Models.DataWarehouseSavedQueryMinimal_columns>(global::Soenneker.PostHog.OpenApiClient.Models.DataWarehouseSavedQueryMinimal_columns.CreateFromDiscriminatorValue)?.AsList(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "created_by", n => { CreatedBy = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.UserBasic>(global::Soenneker.PostHog.OpenApiClient.Models.UserBasic.CreateFromDiscriminatorValue); } },
                { "deleted", n => { Deleted = n.GetBoolValue(); } },
                { "expires_at", n => { ExpiresAt = n.GetDateTimeOffsetValue(); } },
                { "folder_id", n => { FolderId = n.GetGuidValue(); } },
                { "folder_name", n => { FolderName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "is_materialized", n => { IsMaterialized = n.GetBoolValue(); } },
                { "is_test", n => { IsTest = n.GetBoolValue(); } },
                { "last_run_at", n => { LastRunAt = n.GetDateTimeOffsetValue(); } },
                { "latest_error", n => { LatestError = n.GetStringValue(); } },
                { "managed_viewset_kind", n => { ManagedViewsetKind = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "origin", n => { Origin = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.DataWarehouseSavedQueryMinimal.DataWarehouseSavedQueryMinimal_origin>(global::Soenneker.PostHog.OpenApiClient.Models.DataWarehouseSavedQueryMinimal.DataWarehouseSavedQueryMinimal_origin.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.DataWarehouseSavedQueryMinimal.DataWarehouseSavedQueryMinimal_status>(global::Soenneker.PostHog.OpenApiClient.Models.DataWarehouseSavedQueryMinimal.DataWarehouseSavedQueryMinimal_status.CreateFromDiscriminatorValue); } },
                { "sync_frequency", n => { SyncFrequency = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.PostHog.OpenApiClient.Models.NullEnum"/>, <see cref="global::Soenneker.PostHog.OpenApiClient.Models.OriginEnum"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DataWarehouseSavedQueryMinimal_origin : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.NullEnum"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.PostHog.OpenApiClient.Models.NullEnum? NullEnum { get; set; }
#nullable restore
#else
            public global::Soenneker.PostHog.OpenApiClient.Models.NullEnum NullEnum { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.OriginEnum"/></summary>
            public global::Soenneker.PostHog.OpenApiClient.Models.OriginEnum? OriginEnum { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.DataWarehouseSavedQueryMinimal.DataWarehouseSavedQueryMinimal_origin"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.PostHog.OpenApiClient.Models.DataWarehouseSavedQueryMinimal.DataWarehouseSavedQueryMinimal_origin CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.PostHog.OpenApiClient.Models.DataWarehouseSavedQueryMinimal.DataWarehouseSavedQueryMinimal_origin();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.NullEnum = new global::Soenneker.PostHog.OpenApiClient.Models.NullEnum();
                }
                else if(parseNode.GetEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.OriginEnum>() is global::Soenneker.PostHog.OpenApiClient.Models.OriginEnum originEnumValue)
                {
                    result.OriginEnum = originEnumValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(NullEnum != null)
                {
                    return NullEnum.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(NullEnum != null)
                {
                    writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.NullEnum>(null, NullEnum);
                }
                else if(OriginEnum != null)
                {
                    writer.WriteEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.OriginEnum>(null, OriginEnum);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.PostHog.OpenApiClient.Models.NullEnum"/>, <see cref="global::Soenneker.PostHog.OpenApiClient.Models.SavedQueryStatusEnum"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DataWarehouseSavedQueryMinimal_status : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.NullEnum"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.PostHog.OpenApiClient.Models.NullEnum? NullEnum { get; set; }
#nullable restore
#else
            public global::Soenneker.PostHog.OpenApiClient.Models.NullEnum NullEnum { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.SavedQueryStatusEnum"/></summary>
            public global::Soenneker.PostHog.OpenApiClient.Models.SavedQueryStatusEnum? SavedQueryStatusEnum { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.DataWarehouseSavedQueryMinimal.DataWarehouseSavedQueryMinimal_status"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.PostHog.OpenApiClient.Models.DataWarehouseSavedQueryMinimal.DataWarehouseSavedQueryMinimal_status CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.PostHog.OpenApiClient.Models.DataWarehouseSavedQueryMinimal.DataWarehouseSavedQueryMinimal_status();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.NullEnum = new global::Soenneker.PostHog.OpenApiClient.Models.NullEnum();
                }
                else if(parseNode.GetEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.SavedQueryStatusEnum>() is global::Soenneker.PostHog.OpenApiClient.Models.SavedQueryStatusEnum savedQueryStatusEnumValue)
                {
                    result.SavedQueryStatusEnum = savedQueryStatusEnumValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(NullEnum != null)
                {
                    return NullEnum.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(NullEnum != null)
                {
                    writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.NullEnum>(null, NullEnum);
                }
                else if(SavedQueryStatusEnum != null)
                {
                    writer.WriteEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.SavedQueryStatusEnum>(null, SavedQueryStatusEnum);
                }
            }
        }
    }
}
#pragma warning restore CS0618
