// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ErrorTrackingFingerprintProjectionQueryKind
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ErrorTrackingFingerprintProjectionQuery")]
        #pragma warning disable CS1591
        ErrorTrackingFingerprintProjectionQuery,
        #pragma warning restore CS1591
    }
}
