// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    /// <summary>* `generation` - Generation* `trace` - Trace* `session` - Session</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EvaluationTargetEnum
    {
        [EnumMember(Value = "generation")]
        #pragma warning disable CS1591
        Generation,
        #pragma warning restore CS1591
        [EnumMember(Value = "trace")]
        #pragma warning disable CS1591
        Trace,
        #pragma warning restore CS1591
        [EnumMember(Value = "session")]
        #pragma warning disable CS1591
        Session,
        #pragma warning restore CS1591
    }
}
