// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.PostHog.OpenApiClient.Models.BaseMathTypeWrapper6"/>, <see cref="global::Soenneker.PostHog.OpenApiClient.Models.CalendarHeatmapMathTypeWrapper6"/>, <see cref="global::Soenneker.PostHog.OpenApiClient.Models.CountPerActorMathTypeWrapper6"/>, <see cref="global::Soenneker.PostHog.OpenApiClient.Models.EventsNodeMathMember1"/>, <see cref="global::Soenneker.PostHog.OpenApiClient.Models.ExperimentMetricMathTypeWrapper6"/>, <see cref="global::Soenneker.PostHog.OpenApiClient.Models.FunnelMathTypeWrapper6"/>, <see cref="global::Soenneker.PostHog.OpenApiClient.Models.GroupMathTypeWrapper6"/>, <see cref="global::Soenneker.PostHog.OpenApiClient.Models.MathObject"/>, <see cref="global::Soenneker.PostHog.OpenApiClient.Models.PropertyMathTypeWrapper6"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EventsNodeMath : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.BaseMathTypeWrapper6"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.BaseMathTypeWrapper6? BaseMathTypeWrapper6 { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.BaseMathTypeWrapper6 BaseMathTypeWrapper6 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.CalendarHeatmapMathTypeWrapper6"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.CalendarHeatmapMathTypeWrapper6? CalendarHeatmapMathTypeWrapper6 { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.CalendarHeatmapMathTypeWrapper6 CalendarHeatmapMathTypeWrapper6 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.CountPerActorMathTypeWrapper6"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.CountPerActorMathTypeWrapper6? CountPerActorMathTypeWrapper6 { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.CountPerActorMathTypeWrapper6 CountPerActorMathTypeWrapper6 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.EventsNodeMathMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.EventsNodeMathMember1? EventsNodeMathMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.EventsNodeMathMember1 EventsNodeMathMember1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.ExperimentMetricMathTypeWrapper6"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.ExperimentMetricMathTypeWrapper6? ExperimentMetricMathTypeWrapper6 { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.ExperimentMetricMathTypeWrapper6 ExperimentMetricMathTypeWrapper6 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.FunnelMathTypeWrapper6"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.FunnelMathTypeWrapper6? FunnelMathTypeWrapper6 { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.FunnelMathTypeWrapper6 FunnelMathTypeWrapper6 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.GroupMathTypeWrapper6"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.GroupMathTypeWrapper6? GroupMathTypeWrapper6 { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.GroupMathTypeWrapper6 GroupMathTypeWrapper6 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.MathObject"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.MathObject? Math { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.MathObject Math { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.PropertyMathTypeWrapper6"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.PropertyMathTypeWrapper6? PropertyMathTypeWrapper6 { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.PropertyMathTypeWrapper6 PropertyMathTypeWrapper6 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.EventsNodeMath"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PostHog.OpenApiClient.Models.EventsNodeMath CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.PostHog.OpenApiClient.Models.EventsNodeMath();
            result.BaseMathTypeWrapper6 = new global::Soenneker.PostHog.OpenApiClient.Models.BaseMathTypeWrapper6();
            result.CalendarHeatmapMathTypeWrapper6 = new global::Soenneker.PostHog.OpenApiClient.Models.CalendarHeatmapMathTypeWrapper6();
            result.CountPerActorMathTypeWrapper6 = new global::Soenneker.PostHog.OpenApiClient.Models.CountPerActorMathTypeWrapper6();
            result.EventsNodeMathMember1 = new global::Soenneker.PostHog.OpenApiClient.Models.EventsNodeMathMember1();
            result.ExperimentMetricMathTypeWrapper6 = new global::Soenneker.PostHog.OpenApiClient.Models.ExperimentMetricMathTypeWrapper6();
            result.FunnelMathTypeWrapper6 = new global::Soenneker.PostHog.OpenApiClient.Models.FunnelMathTypeWrapper6();
            result.GroupMathTypeWrapper6 = new global::Soenneker.PostHog.OpenApiClient.Models.GroupMathTypeWrapper6();
            result.Math = new global::Soenneker.PostHog.OpenApiClient.Models.MathObject();
            result.PropertyMathTypeWrapper6 = new global::Soenneker.PostHog.OpenApiClient.Models.PropertyMathTypeWrapper6();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(BaseMathTypeWrapper6 != null || CalendarHeatmapMathTypeWrapper6 != null || CountPerActorMathTypeWrapper6 != null || EventsNodeMathMember1 != null || ExperimentMetricMathTypeWrapper6 != null || FunnelMathTypeWrapper6 != null || GroupMathTypeWrapper6 != null || Math != null || PropertyMathTypeWrapper6 != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(BaseMathTypeWrapper6, CalendarHeatmapMathTypeWrapper6, CountPerActorMathTypeWrapper6, EventsNodeMathMember1, ExperimentMetricMathTypeWrapper6, FunnelMathTypeWrapper6, GroupMathTypeWrapper6, Math, PropertyMathTypeWrapper6);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.BaseMathTypeWrapper6>(null, BaseMathTypeWrapper6, CalendarHeatmapMathTypeWrapper6, CountPerActorMathTypeWrapper6, EventsNodeMathMember1, ExperimentMetricMathTypeWrapper6, FunnelMathTypeWrapper6, GroupMathTypeWrapper6, Math, PropertyMathTypeWrapper6);
        }
    }
}
#pragma warning restore CS0618
