// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ExperimentQueryResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The baseline property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.ExperimentStatsBaseValidated? Baseline { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.ExperimentStatsBaseValidated Baseline { get; set; }
#endif
        /// <summary>Results grouped by breakdown value. When present, baseline and variant_results contain aggregated data.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentBreakdownResult>? BreakdownResults { get; set; }
#nullable restore
#else
        public List<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentBreakdownResult> BreakdownResults { get; set; }
#endif
        /// <summary>The clickhouse_sql property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClickhouseSql { get; set; }
#nullable restore
#else
        public string ClickhouseSql { get; set; }
#endif
        /// <summary>The credible_intervals property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseCredibleIntervalsProperty? CredibleIntervals { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseCredibleIntervalsProperty CredibleIntervals { get; set; }
#endif
        /// <summary>The hogql property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Hogql { get; set; }
#nullable restore
#else
        public string Hogql { get; set; }
#endif
        /// <summary>The insight property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseInsight? Insight { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseInsight Insight { get; set; }
#endif
        /// <summary>Whether exposures were served from the precomputation system</summary>
        public bool? IsPrecomputed { get; set; }
        /// <summary>The kind property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Kind { get; set; }
#nullable restore
#else
        public string Kind { get; set; }
#endif
        /// <summary>The metric property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseMetricAnyOf1? Metric { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseMetricAnyOf1 Metric { get; set; }
#endif
        /// <summary>The probability property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseProbabilityProperty? Probability { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseProbabilityProperty Probability { get; set; }
#endif
        /// <summary>The p_value property</summary>
        public double? PValue { get; set; }
        /// <summary>The significance_code property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.ExperimentSignificanceCodeWrapper? SignificanceCode { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.ExperimentSignificanceCodeWrapper SignificanceCode { get; set; }
#endif
        /// <summary>The significant property</summary>
        public bool? Significant { get; set; }
        /// <summary>The stats_version property</summary>
        public int? StatsVersion { get; set; }
        /// <summary>The variant_results property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseVariantResults? VariantResults { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseVariantResults VariantResults { get; set; }
#endif
        /// <summary>The variants property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseVariants? Variants { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseVariants Variants { get; set; }
#endif
        /// <summary>Data warehouse sync warnings — see AnalyticsQueryResponseBase.warnings for semantics.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PostHog.OpenApiClient.Models.DataWarehouseSyncWarning>? Warnings { get; set; }
#nullable restore
#else
        public List<global::Soenneker.PostHog.OpenApiClient.Models.DataWarehouseSyncWarning> Warnings { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "baseline", n => { Baseline = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentStatsBaseValidated>(global::Soenneker.PostHog.OpenApiClient.Models.ExperimentStatsBaseValidated.CreateFromDiscriminatorValue); } },
                { "breakdown_results", n => { BreakdownResults = n.GetCollectionOfObjectValues<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentBreakdownResult>(global::Soenneker.PostHog.OpenApiClient.Models.ExperimentBreakdownResult.CreateFromDiscriminatorValue)?.AsList(); } },
                { "clickhouse_sql", n => { ClickhouseSql = n.GetStringValue(); } },
                { "credible_intervals", n => { CredibleIntervals = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseCredibleIntervalsProperty>(global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseCredibleIntervalsProperty.CreateFromDiscriminatorValue); } },
                { "hogql", n => { Hogql = n.GetStringValue(); } },
                { "insight", n => { Insight = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseInsight>(global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseInsight.CreateFromDiscriminatorValue); } },
                { "is_precomputed", n => { IsPrecomputed = n.GetBoolValue(); } },
                { "kind", n => { Kind = n.GetStringValue(); } },
                { "metric", n => { Metric = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseMetricAnyOf1>(global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseMetricAnyOf1.CreateFromDiscriminatorValue); } },
                { "p_value", n => { PValue = n.GetDoubleValue(); } },
                { "probability", n => { Probability = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseProbabilityProperty>(global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseProbabilityProperty.CreateFromDiscriminatorValue); } },
                { "significance_code", n => { SignificanceCode = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentSignificanceCodeWrapper>(global::Soenneker.PostHog.OpenApiClient.Models.ExperimentSignificanceCodeWrapper.CreateFromDiscriminatorValue); } },
                { "significant", n => { Significant = n.GetBoolValue(); } },
                { "stats_version", n => { StatsVersion = n.GetIntValue(); } },
                { "variant_results", n => { VariantResults = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseVariantResults>(global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseVariantResults.CreateFromDiscriminatorValue); } },
                { "variants", n => { Variants = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseVariants>(global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseVariants.CreateFromDiscriminatorValue); } },
                { "warnings", n => { Warnings = n.GetCollectionOfObjectValues<global::Soenneker.PostHog.OpenApiClient.Models.DataWarehouseSyncWarning>(global::Soenneker.PostHog.OpenApiClient.Models.DataWarehouseSyncWarning.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentStatsBaseValidated>("baseline", Baseline);
            writer.WriteCollectionOfObjectValues<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentBreakdownResult>("breakdown_results", BreakdownResults);
            writer.WriteStringValue("clickhouse_sql", ClickhouseSql);
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseCredibleIntervalsProperty>("credible_intervals", CredibleIntervals);
            writer.WriteStringValue("hogql", Hogql);
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseInsight>("insight", Insight);
            writer.WriteBoolValue("is_precomputed", IsPrecomputed);
            writer.WriteStringValue("kind", Kind);
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseMetricAnyOf1>("metric", Metric);
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseProbabilityProperty>("probability", Probability);
            writer.WriteDoubleValue("p_value", PValue);
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentSignificanceCodeWrapper>("significance_code", SignificanceCode);
            writer.WriteBoolValue("significant", Significant);
            writer.WriteIntValue("stats_version", StatsVersion);
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseVariantResults>("variant_results", VariantResults);
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentQueryResponseVariants>("variants", Variants);
            writer.WriteCollectionOfObjectValues<global::Soenneker.PostHog.OpenApiClient.Models.DataWarehouseSyncWarning>("warnings", Warnings);
        }
    }
}
#pragma warning restore CS0618
