// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ExperimentFunnelMetric : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The breakdownFilter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.BreakdownFilter? BreakdownFilter { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.BreakdownFilter BreakdownFilter { get; set; }
#endif
        /// <summary>The conversion_window property</summary>
        public int? ConversionWindow { get; set; }
        /// <summary>The conversion_window_unit property</summary>
        public global::Soenneker.PostHog.OpenApiClient.Models.FunnelConversionWindowTimeUnit? ConversionWindowUnit { get; set; }
        /// <summary>The fingerprint property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Fingerprint { get; set; }
#nullable restore
#else
        public string Fingerprint { get; set; }
#endif
        /// <summary>The funnel_order_type property</summary>
        public global::Soenneker.PostHog.OpenApiClient.Models.StepOrderValue? FunnelOrderType { get; set; }
        /// <summary>The goal property</summary>
        public global::Soenneker.PostHog.OpenApiClient.Models.ExperimentMetricGoal? Goal { get; set; }
        /// <summary>The isSharedMetric property</summary>
        public bool? IsSharedMetric { get; set; }
        /// <summary>The kind property</summary>
        public global::Soenneker.PostHog.OpenApiClient.Models.ExperimentFunnelMetric_kind? Kind { get; set; }
        /// <summary>The metric_type property</summary>
        public global::Soenneker.PostHog.OpenApiClient.Models.ExperimentFunnelMetric_metric_type? MetricType { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The response property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.ExperimentFunnelMetric_response? Response { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.ExperimentFunnelMetric_response Response { get; set; }
#endif
        /// <summary>The series property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentFunnelMetric.ExperimentFunnelMetric_series>? Series { get; set; }
#nullable restore
#else
        public List<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentFunnelMetric.ExperimentFunnelMetric_series> Series { get; set; }
#endif
        /// <summary>The sharedMetricId property</summary>
        public double? SharedMetricId { get; set; }
        /// <summary>The uuid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uuid { get; set; }
#nullable restore
#else
        public string Uuid { get; set; }
#endif
        /// <summary>version of the node, used for schema migrations</summary>
        public double? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Models.ExperimentFunnelMetric"/> and sets the default values.
        /// </summary>
        public ExperimentFunnelMetric()
        {
            Kind = global::Soenneker.PostHog.OpenApiClient.Models.ExperimentFunnelMetric_kind.ExperimentMetric;
            MetricType = global::Soenneker.PostHog.OpenApiClient.Models.ExperimentFunnelMetric_metric_type.Funnel;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.ExperimentFunnelMetric"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PostHog.OpenApiClient.Models.ExperimentFunnelMetric CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PostHog.OpenApiClient.Models.ExperimentFunnelMetric();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "breakdownFilter", n => { BreakdownFilter = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.BreakdownFilter>(global::Soenneker.PostHog.OpenApiClient.Models.BreakdownFilter.CreateFromDiscriminatorValue); } },
                { "conversion_window", n => { ConversionWindow = n.GetIntValue(); } },
                { "conversion_window_unit", n => { ConversionWindowUnit = n.GetEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.FunnelConversionWindowTimeUnit>(); } },
                { "fingerprint", n => { Fingerprint = n.GetStringValue(); } },
                { "funnel_order_type", n => { FunnelOrderType = n.GetEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.StepOrderValue>(); } },
                { "goal", n => { Goal = n.GetEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentMetricGoal>(); } },
                { "isSharedMetric", n => { IsSharedMetric = n.GetBoolValue(); } },
                { "kind", n => { Kind = n.GetEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentFunnelMetric_kind>(); } },
                { "metric_type", n => { MetricType = n.GetEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentFunnelMetric_metric_type>(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "response", n => { Response = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentFunnelMetric_response>(global::Soenneker.PostHog.OpenApiClient.Models.ExperimentFunnelMetric_response.CreateFromDiscriminatorValue); } },
                { "series", n => { Series = n.GetCollectionOfObjectValues<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentFunnelMetric.ExperimentFunnelMetric_series>(global::Soenneker.PostHog.OpenApiClient.Models.ExperimentFunnelMetric.ExperimentFunnelMetric_series.CreateFromDiscriminatorValue)?.AsList(); } },
                { "sharedMetricId", n => { SharedMetricId = n.GetDoubleValue(); } },
                { "uuid", n => { Uuid = n.GetStringValue(); } },
                { "version", n => { Version = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.BreakdownFilter>("breakdownFilter", BreakdownFilter);
            writer.WriteIntValue("conversion_window", ConversionWindow);
            writer.WriteEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.FunnelConversionWindowTimeUnit>("conversion_window_unit", ConversionWindowUnit);
            writer.WriteStringValue("fingerprint", Fingerprint);
            writer.WriteEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.StepOrderValue>("funnel_order_type", FunnelOrderType);
            writer.WriteEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentMetricGoal>("goal", Goal);
            writer.WriteBoolValue("isSharedMetric", IsSharedMetric);
            writer.WriteEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentFunnelMetric_kind>("kind", Kind);
            writer.WriteEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentFunnelMetric_metric_type>("metric_type", MetricType);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentFunnelMetric_response>("response", Response);
            writer.WriteCollectionOfObjectValues<global::Soenneker.PostHog.OpenApiClient.Models.ExperimentFunnelMetric.ExperimentFunnelMetric_series>("series", Series);
            writer.WriteDoubleValue("sharedMetricId", SharedMetricId);
            writer.WriteStringValue("uuid", Uuid);
            writer.WriteDoubleValue("version", Version);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.PostHog.OpenApiClient.Models.ActionsNode"/>, <see cref="global::Soenneker.PostHog.OpenApiClient.Models.EventsNode"/>, <see cref="global::Soenneker.PostHog.OpenApiClient.Models.ExperimentDataWarehouseNode"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ExperimentFunnelMetric_series : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.ActionsNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.PostHog.OpenApiClient.Models.ActionsNode? ActionsNode { get; set; }
#nullable restore
#else
            public global::Soenneker.PostHog.OpenApiClient.Models.ActionsNode ActionsNode { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.EventsNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.PostHog.OpenApiClient.Models.EventsNode? EventsNode { get; set; }
#nullable restore
#else
            public global::Soenneker.PostHog.OpenApiClient.Models.EventsNode EventsNode { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.ExperimentDataWarehouseNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.PostHog.OpenApiClient.Models.ExperimentDataWarehouseNode? ExperimentDataWarehouseNode { get; set; }
#nullable restore
#else
            public global::Soenneker.PostHog.OpenApiClient.Models.ExperimentDataWarehouseNode ExperimentDataWarehouseNode { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.ExperimentFunnelMetric.ExperimentFunnelMetric_series"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.PostHog.OpenApiClient.Models.ExperimentFunnelMetric.ExperimentFunnelMetric_series CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.PostHog.OpenApiClient.Models.ExperimentFunnelMetric.ExperimentFunnelMetric_series();
                result.ActionsNode = new global::Soenneker.PostHog.OpenApiClient.Models.ActionsNode();
                result.EventsNode = new global::Soenneker.PostHog.OpenApiClient.Models.EventsNode();
                result.ExperimentDataWarehouseNode = new global::Soenneker.PostHog.OpenApiClient.Models.ExperimentDataWarehouseNode();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ActionsNode != null || EventsNode != null || ExperimentDataWarehouseNode != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ActionsNode, EventsNode, ExperimentDataWarehouseNode);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.ActionsNode>(null, ActionsNode, EventsNode, ExperimentDataWarehouseNode);
            }
        }
    }
}
#pragma warning restore CS0618
