// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    /// <summary>
    /// Fleet-wide tally of recent scout output — legacy `emit_signal` findings plus reportsauthored/edited via the report channel. Backs the &quot;Scout findings&quot; callout so it rendersfrom one cheap query instead of the client walking the whole paginated runs window.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FleetFindingsSummary : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Number of distinct inbox reports scouts authored via `emit_report`, deduped across runs, over the same most-recent-120-output-runs set as `count`, capped to the 50 most recently touched reports (the same slice the findings page lists).</summary>
        public int? AuthoredReportCount { get; set; }
        /// <summary>Total findings the fleet emitted in the window — the sum of each run&apos;s `emitted_count`, over the most recent 120 runs that produced output.</summary>
        public int? Count { get; set; }
        /// <summary>Number of distinct inbox reports scouts edited via `edit_report`, deduped across runs, over the same most-recent-120-output-runs set as `count`, capped to the 50 most recently touched reports (the same slice the findings page lists) and excluding reports also authored within that set (authoring supersedes an edit; a report whose authoring run falls outside the cap counts as edited).</summary>
        public int? EditedReportCount { get; set; }
        /// <summary>ISO-8601 timestamp of the most recent output run (TaskRun completion, falling back to run creation), or null when nothing was produced in the window.</summary>
        public DateTimeOffset? LatestAt { get; set; }
        /// <summary>Number of distinct scouts (skills) that produced output in the window — emitted a finding, or authored/edited an inbox report that survives the 50-report cap (a report-only scout whose touched reports all fell outside the cap is not counted, matching the findings page&apos;s scout filter).</summary>
        public int? ScoutCount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Models.FleetFindingsSummary"/> and sets the default values.
        /// </summary>
        public FleetFindingsSummary()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.FleetFindingsSummary"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PostHog.OpenApiClient.Models.FleetFindingsSummary CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PostHog.OpenApiClient.Models.FleetFindingsSummary();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "authored_report_count", n => { AuthoredReportCount = n.GetIntValue(); } },
                { "count", n => { Count = n.GetIntValue(); } },
                { "edited_report_count", n => { EditedReportCount = n.GetIntValue(); } },
                { "latest_at", n => { LatestAt = n.GetDateTimeOffsetValue(); } },
                { "scout_count", n => { ScoutCount = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("authored_report_count", AuthoredReportCount);
            writer.WriteIntValue("count", Count);
            writer.WriteIntValue("edited_report_count", EditedReportCount);
            writer.WriteDateTimeOffsetValue("latest_at", LatestAt);
            writer.WriteIntValue("scout_count", ScoutCount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
