// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.PostHog.OpenApiClient.Models.BaseMathTypeWrapper9"/>, <see cref="global::Soenneker.PostHog.OpenApiClient.Models.CalendarHeatmapMathTypeWrapper9"/>, <see cref="global::Soenneker.PostHog.OpenApiClient.Models.CountPerActorMathTypeWrapper9"/>, <see cref="global::Soenneker.PostHog.OpenApiClient.Models.ExperimentMetricMathTypeWrapper10"/>, <see cref="global::Soenneker.PostHog.OpenApiClient.Models.FunnelExclusionEventsNodeMathMember1"/>, <see cref="global::Soenneker.PostHog.OpenApiClient.Models.FunnelMathTypeWrapper9"/>, <see cref="global::Soenneker.PostHog.OpenApiClient.Models.GroupMathTypeWrapper9"/>, <see cref="global::Soenneker.PostHog.OpenApiClient.Models.MathObject"/>, <see cref="global::Soenneker.PostHog.OpenApiClient.Models.PropertyMathTypeWrapper9"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FunnelExclusionEventsNodeMath : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.BaseMathTypeWrapper9"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.BaseMathTypeWrapper9? BaseMathTypeWrapper9 { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.BaseMathTypeWrapper9 BaseMathTypeWrapper9 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.CalendarHeatmapMathTypeWrapper9"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.CalendarHeatmapMathTypeWrapper9? CalendarHeatmapMathTypeWrapper9 { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.CalendarHeatmapMathTypeWrapper9 CalendarHeatmapMathTypeWrapper9 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.CountPerActorMathTypeWrapper9"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.CountPerActorMathTypeWrapper9? CountPerActorMathTypeWrapper9 { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.CountPerActorMathTypeWrapper9 CountPerActorMathTypeWrapper9 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.ExperimentMetricMathTypeWrapper10"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.ExperimentMetricMathTypeWrapper10? ExperimentMetricMathTypeWrapper10 { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.ExperimentMetricMathTypeWrapper10 ExperimentMetricMathTypeWrapper10 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.FunnelExclusionEventsNodeMathMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.FunnelExclusionEventsNodeMathMember1? FunnelExclusionEventsNodeMathMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.FunnelExclusionEventsNodeMathMember1 FunnelExclusionEventsNodeMathMember1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.FunnelMathTypeWrapper9"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.FunnelMathTypeWrapper9? FunnelMathTypeWrapper9 { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.FunnelMathTypeWrapper9 FunnelMathTypeWrapper9 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.GroupMathTypeWrapper9"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.GroupMathTypeWrapper9? GroupMathTypeWrapper9 { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.GroupMathTypeWrapper9 GroupMathTypeWrapper9 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.MathObject"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.MathObject? Math { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.MathObject Math { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.PropertyMathTypeWrapper9"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.PropertyMathTypeWrapper9? PropertyMathTypeWrapper9 { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.PropertyMathTypeWrapper9 PropertyMathTypeWrapper9 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.FunnelExclusionEventsNodeMath"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PostHog.OpenApiClient.Models.FunnelExclusionEventsNodeMath CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.PostHog.OpenApiClient.Models.FunnelExclusionEventsNodeMath();
            result.BaseMathTypeWrapper9 = new global::Soenneker.PostHog.OpenApiClient.Models.BaseMathTypeWrapper9();
            result.CalendarHeatmapMathTypeWrapper9 = new global::Soenneker.PostHog.OpenApiClient.Models.CalendarHeatmapMathTypeWrapper9();
            result.CountPerActorMathTypeWrapper9 = new global::Soenneker.PostHog.OpenApiClient.Models.CountPerActorMathTypeWrapper9();
            result.ExperimentMetricMathTypeWrapper10 = new global::Soenneker.PostHog.OpenApiClient.Models.ExperimentMetricMathTypeWrapper10();
            result.FunnelExclusionEventsNodeMathMember1 = new global::Soenneker.PostHog.OpenApiClient.Models.FunnelExclusionEventsNodeMathMember1();
            result.FunnelMathTypeWrapper9 = new global::Soenneker.PostHog.OpenApiClient.Models.FunnelMathTypeWrapper9();
            result.GroupMathTypeWrapper9 = new global::Soenneker.PostHog.OpenApiClient.Models.GroupMathTypeWrapper9();
            result.Math = new global::Soenneker.PostHog.OpenApiClient.Models.MathObject();
            result.PropertyMathTypeWrapper9 = new global::Soenneker.PostHog.OpenApiClient.Models.PropertyMathTypeWrapper9();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(BaseMathTypeWrapper9 != null || CalendarHeatmapMathTypeWrapper9 != null || CountPerActorMathTypeWrapper9 != null || ExperimentMetricMathTypeWrapper10 != null || FunnelExclusionEventsNodeMathMember1 != null || FunnelMathTypeWrapper9 != null || GroupMathTypeWrapper9 != null || Math != null || PropertyMathTypeWrapper9 != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(BaseMathTypeWrapper9, CalendarHeatmapMathTypeWrapper9, CountPerActorMathTypeWrapper9, ExperimentMetricMathTypeWrapper10, FunnelExclusionEventsNodeMathMember1, FunnelMathTypeWrapper9, GroupMathTypeWrapper9, Math, PropertyMathTypeWrapper9);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.BaseMathTypeWrapper9>(null, BaseMathTypeWrapper9, CalendarHeatmapMathTypeWrapper9, CountPerActorMathTypeWrapper9, ExperimentMetricMathTypeWrapper10, FunnelExclusionEventsNodeMathMember1, FunnelMathTypeWrapper9, GroupMathTypeWrapper9, Math, PropertyMathTypeWrapper9);
        }
    }
}
#pragma warning restore CS0618
