// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.PostHog.OpenApiClient.Models.DataTableNode"/>, <see cref="global::Soenneker.PostHog.OpenApiClient.Models.DataVisualizationNode"/>, <see cref="global::Soenneker.PostHog.OpenApiClient.Models.HogQuery"/>, <see cref="global::Soenneker.PostHog.OpenApiClient.Models.InsightVizNode"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InsightQuerySchema : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.DataTableNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.DataTableNode? DataTableNode { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.DataTableNode DataTableNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.DataVisualizationNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.DataVisualizationNode? DataVisualizationNode { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.DataVisualizationNode DataVisualizationNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.HogQuery"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.HogQuery? HogQuery { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.HogQuery HogQuery { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.InsightVizNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.InsightVizNode? InsightVizNode { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.InsightVizNode InsightVizNode { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.InsightQuerySchema"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PostHog.OpenApiClient.Models.InsightQuerySchema CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("kind")?.GetStringValue();
            var result = new global::Soenneker.PostHog.OpenApiClient.Models.InsightQuerySchema();
            if("DataTableNode".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DataTableNode = new global::Soenneker.PostHog.OpenApiClient.Models.DataTableNode();
            }
            else if("DataVisualizationNode".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DataVisualizationNode = new global::Soenneker.PostHog.OpenApiClient.Models.DataVisualizationNode();
            }
            else if("HogQuery".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.HogQuery = new global::Soenneker.PostHog.OpenApiClient.Models.HogQuery();
            }
            else if("InsightVizNode".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.InsightVizNode = new global::Soenneker.PostHog.OpenApiClient.Models.InsightVizNode();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(DataTableNode != null)
            {
                return DataTableNode.GetFieldDeserializers();
            }
            else if(DataVisualizationNode != null)
            {
                return DataVisualizationNode.GetFieldDeserializers();
            }
            else if(HogQuery != null)
            {
                return HogQuery.GetFieldDeserializers();
            }
            else if(InsightVizNode != null)
            {
                return InsightVizNode.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(DataTableNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.DataTableNode>(null, DataTableNode);
            }
            else if(DataVisualizationNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.DataVisualizationNode>(null, DataVisualizationNode);
            }
            else if(HogQuery != null)
            {
                writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.HogQuery>(null, HogQuery);
            }
            else if(InsightVizNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.InsightVizNode>(null, InsightVizNode);
            }
        }
    }
}
#pragma warning restore CS0618
