// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MarketingAnalyticsRetentionQuery : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Groups aggregation - not used in Web Analytics but required for type compatibility</summary>
        public int? AggregationGroupTypeIndex { get; set; }
        /// <summary>Cohort dimension, read off each person&apos;s first session. Defaults to channel.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.MarketingAnalyticsAttributionBreakdownWrapper3? BreakdownBy { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.MarketingAnalyticsAttributionBreakdownWrapper3 BreakdownBy { get; set; }
#endif
        /// <summary>Breakdown values kept before the rest roll into &apos;Other&apos;. Defaults to 20.</summary>
        public int? BreakdownLimit { get; set; }
        /// <summary>Colors used in the insight&apos;s visualization - not used in Web Analytics but required for type compatibility</summary>
        public double? DataColorTheme { get; set; }
        /// <summary>The dateRange property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.DateRange? DateRange { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.DateRange DateRange { get; set; }
#endif
        /// <summary>Drop direct sessions when deciding first touch, mirroring the attribution explorer.</summary>
        public bool? ExcludeDirectTraffic { get; set; }
        /// <summary>Drop persons whose first session names nothing for the current breakdown.</summary>
        public bool? ExcludeUnattributed { get; set; }
        /// <summary>The filterTestAccounts property</summary>
        public bool? FilterTestAccounts { get; set; }
        /// <summary>The includeRevenue property</summary>
        public bool? IncludeRevenue { get; set; }
        /// <summary>The kind property</summary>
        public global::Soenneker.PostHog.OpenApiClient.Models.MarketingAnalyticsRetentionQueryKind? Kind { get; set; }
        /// <summary>Modifiers used when performing the query</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.HogQlQueryModifiers? Modifiers { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.HogQlQueryModifiers Modifiers { get; set; }
#endif
        /// <summary>How far back to look for a prior session. Defaults to 90, clamped to 365.</summary>
        public int? NewUserLookbackDays { get; set; }
        /// <summary>Only count persons with no session before the range, so a channel&apos;s cohorts are not inflated by users it acquired long ago. Defaults to true.</summary>
        public bool? OnlyNewUsers { get; set; }
        /// <summary>The properties property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PostHog.OpenApiClient.Models.MarketingAnalyticsRetentionQueryPropertiesItem>? Properties { get; set; }
#nullable restore
#else
        public List<global::Soenneker.PostHog.OpenApiClient.Models.MarketingAnalyticsRetentionQueryPropertiesItem> Properties { get; set; }
#endif
        /// <summary>The response property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.MarketingAnalyticsRetentionQueryResponse? Response { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.MarketingAnalyticsRetentionQueryResponse Response { get; set; }
#endif
        /// <summary>Period for both the cohort rows and the return columns. Defaults to week.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.MarketingAnalyticsRetentionIntervalWrapper? RetentionInterval { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.MarketingAnalyticsRetentionIntervalWrapper RetentionInterval { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.QueryLogTags? Tags { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.QueryLogTags Tags { get; set; }
#endif
        /// <summary>Return columns, counting period 0. Defaults to 8, clamped to 40.</summary>
        public int? TotalIntervals { get; set; }
        /// <summary>The useSessionsTable property</summary>
        public bool? UseSessionsTable { get; set; }
        /// <summary>version of the node, used for schema migrations</summary>
        public double? Version { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.MarketingAnalyticsRetentionQuery"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PostHog.OpenApiClient.Models.MarketingAnalyticsRetentionQuery CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PostHog.OpenApiClient.Models.MarketingAnalyticsRetentionQuery();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aggregation_group_type_index", n => { AggregationGroupTypeIndex = n.GetIntValue(); } },
                { "breakdownBy", n => { BreakdownBy = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.MarketingAnalyticsAttributionBreakdownWrapper3>(global::Soenneker.PostHog.OpenApiClient.Models.MarketingAnalyticsAttributionBreakdownWrapper3.CreateFromDiscriminatorValue); } },
                { "breakdownLimit", n => { BreakdownLimit = n.GetIntValue(); } },
                { "dataColorTheme", n => { DataColorTheme = n.GetDoubleValue(); } },
                { "dateRange", n => { DateRange = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.DateRange>(global::Soenneker.PostHog.OpenApiClient.Models.DateRange.CreateFromDiscriminatorValue); } },
                { "excludeDirectTraffic", n => { ExcludeDirectTraffic = n.GetBoolValue(); } },
                { "excludeUnattributed", n => { ExcludeUnattributed = n.GetBoolValue(); } },
                { "filterTestAccounts", n => { FilterTestAccounts = n.GetBoolValue(); } },
                { "includeRevenue", n => { IncludeRevenue = n.GetBoolValue(); } },
                { "kind", n => { Kind = n.GetEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.MarketingAnalyticsRetentionQueryKind>(); } },
                { "modifiers", n => { Modifiers = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.HogQlQueryModifiers>(global::Soenneker.PostHog.OpenApiClient.Models.HogQlQueryModifiers.CreateFromDiscriminatorValue); } },
                { "newUserLookbackDays", n => { NewUserLookbackDays = n.GetIntValue(); } },
                { "onlyNewUsers", n => { OnlyNewUsers = n.GetBoolValue(); } },
                { "properties", n => { Properties = n.GetCollectionOfObjectValues<global::Soenneker.PostHog.OpenApiClient.Models.MarketingAnalyticsRetentionQueryPropertiesItem>(global::Soenneker.PostHog.OpenApiClient.Models.MarketingAnalyticsRetentionQueryPropertiesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "response", n => { Response = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.MarketingAnalyticsRetentionQueryResponse>(global::Soenneker.PostHog.OpenApiClient.Models.MarketingAnalyticsRetentionQueryResponse.CreateFromDiscriminatorValue); } },
                { "retentionInterval", n => { RetentionInterval = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.MarketingAnalyticsRetentionIntervalWrapper>(global::Soenneker.PostHog.OpenApiClient.Models.MarketingAnalyticsRetentionIntervalWrapper.CreateFromDiscriminatorValue); } },
                { "tags", n => { Tags = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.QueryLogTags>(global::Soenneker.PostHog.OpenApiClient.Models.QueryLogTags.CreateFromDiscriminatorValue); } },
                { "totalIntervals", n => { TotalIntervals = n.GetIntValue(); } },
                { "useSessionsTable", n => { UseSessionsTable = n.GetBoolValue(); } },
                { "version", n => { Version = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("aggregation_group_type_index", AggregationGroupTypeIndex);
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.MarketingAnalyticsAttributionBreakdownWrapper3>("breakdownBy", BreakdownBy);
            writer.WriteIntValue("breakdownLimit", BreakdownLimit);
            writer.WriteDoubleValue("dataColorTheme", DataColorTheme);
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.DateRange>("dateRange", DateRange);
            writer.WriteBoolValue("excludeDirectTraffic", ExcludeDirectTraffic);
            writer.WriteBoolValue("excludeUnattributed", ExcludeUnattributed);
            writer.WriteBoolValue("filterTestAccounts", FilterTestAccounts);
            writer.WriteBoolValue("includeRevenue", IncludeRevenue);
            writer.WriteEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.MarketingAnalyticsRetentionQueryKind>("kind", Kind);
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.HogQlQueryModifiers>("modifiers", Modifiers);
            writer.WriteIntValue("newUserLookbackDays", NewUserLookbackDays);
            writer.WriteBoolValue("onlyNewUsers", OnlyNewUsers);
            writer.WriteCollectionOfObjectValues<global::Soenneker.PostHog.OpenApiClient.Models.MarketingAnalyticsRetentionQueryPropertiesItem>("properties", Properties);
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.MarketingAnalyticsRetentionQueryResponse>("response", Response);
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.MarketingAnalyticsRetentionIntervalWrapper>("retentionInterval", RetentionInterval);
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.QueryLogTags>("tags", Tags);
            writer.WriteIntValue("totalIntervals", TotalIntervals);
            writer.WriteBoolValue("useSessionsTable", UseSessionsTable);
            writer.WriteDoubleValue("version", Version);
        }
    }
}
#pragma warning restore CS0618
