// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    /// <summary>* `idle` - Idle* `computing` - Computing* `error` - Error</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum McpIntentClusterSnapshotStatusEnum
    {
        [EnumMember(Value = "idle")]
        #pragma warning disable CS1591
        Idle,
        #pragma warning restore CS1591
        [EnumMember(Value = "computing")]
        #pragma warning disable CS1591
        Computing,
        #pragma warning restore CS1591
        [EnumMember(Value = "error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
    }
}
