// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class McpToolFailureOccurrenceItem : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The distinct_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DistinctId { get; set; }
#nullable restore
#else
        public string DistinctId { get; set; }
#endif
        /// <summary>Sanitized error message captured on the event; empty when the event predates message capture.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorMessage { get; set; }
#nullable restore
#else
        public string ErrorMessage { get; set; }
#endif
        /// <summary>Raw $mcp_error_status as a string; empty when absent.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorStatus { get; set; }
#nullable restore
#else
        public string ErrorStatus { get; set; }
#endif
        /// <summary>Resolved harness label for the call.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Harness { get; set; }
#nullable restore
#else
        public string Harness { get; set; }
#endif
        /// <summary>JSON-encoded intent payload as reported by the client; empty when absent.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Intent { get; set; }
#nullable restore
#else
        public string Intent { get; set; }
#endif
        /// <summary>&quot;Conversation id: $mcp_session_id, falling back to $session_id; empty when neither is set.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SessionId { get; set; }
#nullable restore
#else
        public string SessionId { get; set; }
#endif
        /// <summary>The timestamp property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Timestamp { get; set; }
#nullable restore
#else
        public string Timestamp { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.McpToolFailureOccurrenceItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PostHog.OpenApiClient.Models.McpToolFailureOccurrenceItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PostHog.OpenApiClient.Models.McpToolFailureOccurrenceItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "distinct_id", n => { DistinctId = n.GetStringValue(); } },
                { "error_message", n => { ErrorMessage = n.GetStringValue(); } },
                { "error_status", n => { ErrorStatus = n.GetStringValue(); } },
                { "harness", n => { Harness = n.GetStringValue(); } },
                { "intent", n => { Intent = n.GetStringValue(); } },
                { "session_id", n => { SessionId = n.GetStringValue(); } },
                { "timestamp", n => { Timestamp = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("distinct_id", DistinctId);
            writer.WriteStringValue("error_message", ErrorMessage);
            writer.WriteStringValue("error_status", ErrorStatus);
            writer.WriteStringValue("harness", Harness);
            writer.WriteStringValue("intent", Intent);
            writer.WriteStringValue("session_id", SessionId);
            writer.WriteStringValue("timestamp", Timestamp);
        }
    }
}
#pragma warning restore CS0618
