// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    /// <summary>
    /// The metric query to execute.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MetricQueryRequestQuery : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>&quot;Aggregation applied per time bucket. &apos;rate&apos; (per-second) and &apos;increase&apos; are counter-aware: per-series deltas with Prometheus counter-reset handling, temporality-aware (delta-temporality samples count as-is). &apos;histogram_quantile&apos; interpolates from OTel histogram buckets and requires &apos;quantile&apos;.* `sum` - sum* `avg` - avg* `count` - count* `p95` - p95* `rate` - rate* `increase` - increase* `histogram_quantile` - histogram_quantile&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.MetricQueryBodyAggregation? Aggregation { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.MetricQueryBodyAggregation Aggregation { get; set; }
#endif
        /// <summary>&quot;Full multi-clause form: each clause is an independent metric selection sharing the request&apos;s time grid (maximum 10). Mutually exclusive with &apos;metricName&apos;.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PostHog.OpenApiClient.Models.MetricClause>? Clauses { get; set; }
#nullable restore
#else
        public List<global::Soenneker.PostHog.OpenApiClient.Models.MetricClause> Clauses { get; set; }
#endif
        /// <summary>Lower bound (inclusive) for the query range. ISO 8601.</summary>
        public DateTimeOffset? DateFrom { get; set; }
        /// <summary>Upper bound (exclusive) for the query range. Defaults to now if omitted.</summary>
        public DateTimeOffset? DateTo { get; set; }
        /// <summary>Label predicates ANDed together. Rows must satisfy every filter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PostHog.OpenApiClient.Models.MetricFilter>? Filters { get; set; }
#nullable restore
#else
        public List<global::Soenneker.PostHog.OpenApiClient.Models.MetricFilter> Filters { get; set; }
#endif
        /// <summary>Arithmetic over clause names evaluated server-side per grid point, e.g. &apos;(a - b) / a&apos;. Supports + - * / and parentheses; division by zero yields 0. When set, only the formula result series are returned.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Formula { get; set; }
#nullable restore
#else
        public string Formula { get; set; }
#endif
        /// <summary>Labels to split the result into separate series by. Series share one time grid and are capped at the 100 largest.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PostHog.OpenApiClient.Models.MetricGroupBy>? GroupBy { get; set; }
#nullable restore
#else
        public List<global::Soenneker.PostHog.OpenApiClient.Models.MetricGroupBy> GroupBy { get; set; }
#endif
        /// <summary>Bucket size for the shared time grid. Omit to auto-pick (~60 buckets across the range).* `second` - second* `minute` - minute* `minute_5` - minute_5* `minute_15` - minute_15* `hour` - hour* `hour_6` - hour_6* `day` - day* `week` - week</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.MetricQueryBodyInterval? Interval { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.MetricQueryBodyInterval Interval { get; set; }
#endif
        /// <summary>Exact metric name to query (e.g. &apos;http.server.duration&apos;). Single-clause shorthand — mutually exclusive with &apos;clauses&apos;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MetricName { get; set; }
#nullable restore
#else
        public string MetricName { get; set; }
#endif
        /// <summary>Constrain the query to one metric type. A name can exist as several types (e.g. a counter and a gauge); without this, rows of every type sharing the name are blended into one aggregate. Get the type from &apos;metric-names-list&apos;.* `gauge` - gauge* `sum` - sum* `histogram` - histogram* `exponential_histogram` - exponential_histogram* `summary` - summary</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.MetricQueryBodyMetricType? MetricType { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.MetricQueryBodyMetricType MetricType { get; set; }
#endif
        /// <summary>Quantile in (0, 1) for &apos;histogram_quantile&apos; (e.g. 0.95). Ignored for other aggregations.</summary>
        public double? Quantile { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Models.MetricQueryRequestQuery"/> and sets the default values.
        /// </summary>
        public MetricQueryRequestQuery()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.MetricQueryRequestQuery"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PostHog.OpenApiClient.Models.MetricQueryRequestQuery CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PostHog.OpenApiClient.Models.MetricQueryRequestQuery();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aggregation", n => { Aggregation = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.MetricQueryBodyAggregation>(global::Soenneker.PostHog.OpenApiClient.Models.MetricQueryBodyAggregation.CreateFromDiscriminatorValue); } },
                { "clauses", n => { Clauses = n.GetCollectionOfObjectValues<global::Soenneker.PostHog.OpenApiClient.Models.MetricClause>(global::Soenneker.PostHog.OpenApiClient.Models.MetricClause.CreateFromDiscriminatorValue)?.AsList(); } },
                { "dateFrom", n => { DateFrom = n.GetDateTimeOffsetValue(); } },
                { "dateTo", n => { DateTo = n.GetDateTimeOffsetValue(); } },
                { "filters", n => { Filters = n.GetCollectionOfObjectValues<global::Soenneker.PostHog.OpenApiClient.Models.MetricFilter>(global::Soenneker.PostHog.OpenApiClient.Models.MetricFilter.CreateFromDiscriminatorValue)?.AsList(); } },
                { "formula", n => { Formula = n.GetStringValue(); } },
                { "groupBy", n => { GroupBy = n.GetCollectionOfObjectValues<global::Soenneker.PostHog.OpenApiClient.Models.MetricGroupBy>(global::Soenneker.PostHog.OpenApiClient.Models.MetricGroupBy.CreateFromDiscriminatorValue)?.AsList(); } },
                { "interval", n => { Interval = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.MetricQueryBodyInterval>(global::Soenneker.PostHog.OpenApiClient.Models.MetricQueryBodyInterval.CreateFromDiscriminatorValue); } },
                { "metricName", n => { MetricName = n.GetStringValue(); } },
                { "metricType", n => { MetricType = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.MetricQueryBodyMetricType>(global::Soenneker.PostHog.OpenApiClient.Models.MetricQueryBodyMetricType.CreateFromDiscriminatorValue); } },
                { "quantile", n => { Quantile = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.MetricQueryBodyAggregation>("aggregation", Aggregation);
            writer.WriteCollectionOfObjectValues<global::Soenneker.PostHog.OpenApiClient.Models.MetricClause>("clauses", Clauses);
            writer.WriteDateTimeOffsetValue("dateFrom", DateFrom);
            writer.WriteDateTimeOffsetValue("dateTo", DateTo);
            writer.WriteCollectionOfObjectValues<global::Soenneker.PostHog.OpenApiClient.Models.MetricFilter>("filters", Filters);
            writer.WriteStringValue("formula", Formula);
            writer.WriteCollectionOfObjectValues<global::Soenneker.PostHog.OpenApiClient.Models.MetricGroupBy>("groupBy", GroupBy);
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.MetricQueryBodyInterval>("interval", Interval);
            writer.WriteStringValue("metricName", MetricName);
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.MetricQueryBodyMetricType>("metricType", MetricType);
            writer.WriteDoubleValue("quantile", Quantile);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
