// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.PostHog.OpenApiClient.Models.BlankEnumWrapper14"/>, <see cref="global::Soenneker.PostHog.OpenApiClient.Models.DefaultExperimentStatsMethodEnumWrapper"/>, <see cref="global::Soenneker.PostHog.OpenApiClient.Models.NullEnum"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OrganizationDefaultExperimentStatsMethod : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.BlankEnumWrapper14"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.BlankEnumWrapper14? BlankEnumWrapper14 { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.BlankEnumWrapper14 BlankEnumWrapper14 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.DefaultExperimentStatsMethodEnumWrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.DefaultExperimentStatsMethodEnumWrapper? DefaultExperimentStatsMethodEnumWrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.DefaultExperimentStatsMethodEnumWrapper DefaultExperimentStatsMethodEnumWrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.PostHog.OpenApiClient.Models.NullEnum"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.NullEnum? NullEnum { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.NullEnum NullEnum { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.OrganizationDefaultExperimentStatsMethod"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PostHog.OpenApiClient.Models.OrganizationDefaultExperimentStatsMethod CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.PostHog.OpenApiClient.Models.OrganizationDefaultExperimentStatsMethod();
            if("BlankEnumWrapper14".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.BlankEnumWrapper14 = new global::Soenneker.PostHog.OpenApiClient.Models.BlankEnumWrapper14();
            }
            else if("DefaultExperimentStatsMethodEnumWrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DefaultExperimentStatsMethodEnumWrapper = new global::Soenneker.PostHog.OpenApiClient.Models.DefaultExperimentStatsMethodEnumWrapper();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(BlankEnumWrapper14 != null)
            {
                return BlankEnumWrapper14.GetFieldDeserializers();
            }
            else if(DefaultExperimentStatsMethodEnumWrapper != null)
            {
                return DefaultExperimentStatsMethodEnumWrapper.GetFieldDeserializers();
            }
            else if(NullEnum != null)
            {
                return NullEnum.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(BlankEnumWrapper14 != null)
            {
                writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.BlankEnumWrapper14>(null, BlankEnumWrapper14);
            }
            else if(DefaultExperimentStatsMethodEnumWrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.DefaultExperimentStatsMethodEnumWrapper>(null, DefaultExperimentStatsMethodEnumWrapper);
            }
            else if(NullEnum != null)
            {
                writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.NullEnum>(null, NullEnum);
            }
        }
    }
}
#pragma warning restore CS0618
