// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ParserMode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "cpp_only")]
        #pragma warning disable CS1591
        CppOnly,
        #pragma warning restore CS1591
        [EnumMember(Value = "cpp_with_rust_shadow")]
        #pragma warning disable CS1591
        CppWithRustShadow,
        #pragma warning restore CS1591
        [EnumMember(Value = "cpp_with_rust_py_shadow")]
        #pragma warning disable CS1591
        CppWithRustPyShadow,
        #pragma warning restore CS1591
        [EnumMember(Value = "rust_with_cpp_shadow")]
        #pragma warning disable CS1591
        RustWithCppShadow,
        #pragma warning restore CS1591
        [EnumMember(Value = "rust_only")]
        #pragma warning disable CS1591
        RustOnly,
        #pragma warning restore CS1591
        [EnumMember(Value = "rust_py_only")]
        #pragma warning disable CS1591
        RustPyOnly,
        #pragma warning restore CS1591
        [EnumMember(Value = "rust_py_with_cpp_shadow")]
        #pragma warning disable CS1591
        RustPyWithCppShadow,
        #pragma warning restore CS1591
    }
}
