// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    /// <summary>* `certified` - certified* `deprecated` - deprecated</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ProposedStatusEnum
    {
        [EnumMember(Value = "certified")]
        #pragma warning disable CS1591
        Certified,
        #pragma warning restore CS1591
        [EnumMember(Value = "deprecated")]
        #pragma warning disable CS1591
        Deprecated,
        #pragma warning restore CS1591
    }
}
