// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ReplayLens : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The created_at property</summary>
        public DateTimeOffset? CreatedAt { get; private set; }
        /// <summary>User who created the lens.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.UserBasic? CreatedBy { get; private set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.UserBasic CreatedBy { get; private set; }
#endif
        /// <summary>Free-form description shown in the lens management UI.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>When true, the prompt is augmented with the Signal side mission and the lens emits PostHog Signals.</summary>
        public bool? EmitsSignals { get; set; }
        /// <summary>When false, the reconciler removes the lens&apos;s Temporal schedule. On-demand triggers still work.</summary>
        public bool? Enabled { get; set; }
        /// <summary>The id property</summary>
        public Guid? Id { get; private set; }
        /// <summary>Watermark for the lens&apos;s last scheduled fire. Mirrors Temporal schedule state for recovery.</summary>
        public DateTimeOffset? LastSweptAt { get; private set; }
        /// <summary>Type-specific configuration. Always includes `prompt`; classifiers add `tags`, scorers add `scale`, etc.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? LensConfig { get; set; }
#nullable restore
#else
        public UntypedNode LensConfig { get; set; }
#endif
        /// <summary>What the lens does: monitor, classifier, scorer, summarizer, or indexer.* `monitor` - Monitor* `classifier` - Classifier* `scorer` - Scorer* `summarizer` - Summarizer* `indexer` - Indexer</summary>
        public global::Soenneker.PostHog.OpenApiClient.Models.LensTypeEnum? LensType { get; set; }
        /// <summary>Increments on every config-changing save. Observations snapshot this value.</summary>
        public int? LensVersion { get; private set; }
        /// <summary>Concrete model to use for this lens.* `gemini-3-flash` - Gemini 3 Flash* `gemini-3-flash-lite` - Gemini 3 Flash Lite</summary>
        public global::Soenneker.PostHog.OpenApiClient.Models.LensModelEnum? Model { get; set; }
        /// <summary>Human-readable lens name. Unique within the team.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>LLM provider. v1 is Google-only.* `google` - Google</summary>
        public global::Soenneker.PostHog.OpenApiClient.Models.LensProviderEnum? Provider { get; set; }
        /// <summary>Persisted `RecordingsQuery` shape used to pick candidate sessions. `date_from`/`date_to` are stripped on save — the schedule controls time, not the user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Query { get; set; }
#nullable restore
#else
        public UntypedNode Query { get; set; }
#endif
        /// <summary>0..1 random downsample applied after the query matches. Defaults to 1.0 (no downsampling).</summary>
        public double? SamplingRate { get; set; }
        /// <summary>The updated_at property</summary>
        public DateTimeOffset? UpdatedAt { get; private set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Models.ReplayLens"/> and sets the default values.
        /// </summary>
        public ReplayLens()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.ReplayLens"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PostHog.OpenApiClient.Models.ReplayLens CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PostHog.OpenApiClient.Models.ReplayLens();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "created_by", n => { CreatedBy = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.UserBasic>(global::Soenneker.PostHog.OpenApiClient.Models.UserBasic.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "emits_signals", n => { EmitsSignals = n.GetBoolValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "last_swept_at", n => { LastSweptAt = n.GetDateTimeOffsetValue(); } },
                { "lens_config", n => { LensConfig = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "lens_type", n => { LensType = n.GetEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.LensTypeEnum>(); } },
                { "lens_version", n => { LensVersion = n.GetIntValue(); } },
                { "model", n => { Model = n.GetEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.LensModelEnum>(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "provider", n => { Provider = n.GetEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.LensProviderEnum>(); } },
                { "query", n => { Query = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "sampling_rate", n => { SamplingRate = n.GetDoubleValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("description", Description);
            writer.WriteBoolValue("emits_signals", EmitsSignals);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteObjectValue<UntypedNode>("lens_config", LensConfig);
            writer.WriteEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.LensTypeEnum>("lens_type", LensType);
            writer.WriteEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.LensModelEnum>("model", Model);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.LensProviderEnum>("provider", Provider);
            writer.WriteObjectValue<UntypedNode>("query", Query);
            writer.WriteDoubleValue("sampling_rate", SamplingRate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
