// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ScoutRoleEnum
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "specialist")]
        #pragma warning disable CS1591
        Specialist,
        #pragma warning restore CS1591
        [EnumMember(Value = "operational")]
        #pragma warning disable CS1591
        Operational,
        #pragma warning restore CS1591
    }
}
