// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SdkHealthReport : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>UI-level status — &apos;success&apos; when healthy, &apos;warning&apos; when some SDKs are outdated, &apos;danger&apos; when the majority are outdated.* `success` - success* `warning` - warning* `danger` - danger</summary>
        public global::Soenneker.PostHog.OpenApiClient.Models.HealthEnum? Health { get; set; }
        /// <summary>Number of SDKs that need updating.</summary>
        public int? NeedsUpdatingCount { get; set; }
        /// <summary>&apos;healthy&apos; when no SDKs need updating, &apos;needs_attention&apos; otherwise.* `healthy` - healthy* `needs_attention` - needs_attention</summary>
        public global::Soenneker.PostHog.OpenApiClient.Models.OverallHealthEnum? OverallHealth { get; set; }
        /// <summary>Per-SDK health assessments.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PostHog.OpenApiClient.Models.SdkAssessment>? Sdks { get; set; }
#nullable restore
#else
        public List<global::Soenneker.PostHog.OpenApiClient.Models.SdkAssessment> Sdks { get; set; }
#endif
        /// <summary>Number of distinct PostHog SDKs the project is actively using.</summary>
        public int? TeamSdkCount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Models.SdkHealthReport"/> and sets the default values.
        /// </summary>
        public SdkHealthReport()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.SdkHealthReport"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PostHog.OpenApiClient.Models.SdkHealthReport CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PostHog.OpenApiClient.Models.SdkHealthReport();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "health", n => { Health = n.GetEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.HealthEnum>(); } },
                { "needs_updating_count", n => { NeedsUpdatingCount = n.GetIntValue(); } },
                { "overall_health", n => { OverallHealth = n.GetEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.OverallHealthEnum>(); } },
                { "sdks", n => { Sdks = n.GetCollectionOfObjectValues<global::Soenneker.PostHog.OpenApiClient.Models.SdkAssessment>(global::Soenneker.PostHog.OpenApiClient.Models.SdkAssessment.CreateFromDiscriminatorValue)?.AsList(); } },
                { "team_sdk_count", n => { TeamSdkCount = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.HealthEnum>("health", Health);
            writer.WriteIntValue("needs_updating_count", NeedsUpdatingCount);
            writer.WriteEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.OverallHealthEnum>("overall_health", OverallHealth);
            writer.WriteCollectionOfObjectValues<global::Soenneker.PostHog.OpenApiClient.Models.SdkAssessment>("sdks", Sdks);
            writer.WriteIntValue("team_sdk_count", TeamSdkCount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
