// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SdkReleaseAssessment : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Relative URL path (starting with /project/{id}/) for the Activity &gt; Explore page pre-filtered to events captured with this lib and lib_version over the last 7 days. Combine with the user&apos;s PostHog host (e.g. us.posthog.com) for a clickable link.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActivityPageUrl { get; set; }
#nullable restore
#else
        public string ActivityPageUrl { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Number of events captured with this version in the last 7 days.</summary>
        public int? Count { get; set; }
        /// <summary>Days since this version was released, or null if unknown.</summary>
        public int? DaysSinceRelease { get; set; }
        /// <summary>True when this version equals or exceeds the latest known published version.</summary>
        public bool? IsCurrentOrNewer { get; set; }
        /// <summary>True when this version is flagged as old by age alone (separate from semver rules).</summary>
        public bool? IsOld { get; set; }
        /// <summary>True when this version is flagged as outdated by smart-semver rules.</summary>
        public bool? IsOutdated { get; set; }
        /// <summary>Timestamp of the most recent event seen for this version (ISO 8601).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MaxTimestamp { get; set; }
#nullable restore
#else
        public string MaxTimestamp { get; set; }
#endif
        /// <summary>True if is_outdated OR is_old.</summary>
        public bool? NeedsUpdating { get; set; }
        /// <summary>Human-readable relative release age matching the UI (e.g. &apos;5 months ago&apos;). Null when release_date is unknown.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReleasedAgo { get; set; }
#nullable restore
#else
        public string ReleasedAgo { get; set; }
#endif
        /// <summary>When this version was published on GitHub (ISO 8601), or null if unknown.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReleaseDate { get; set; }
#nullable restore
#else
        public string ReleaseDate { get; set; }
#endif
        /// <summary>SQL SELECT statement for drilling into events for this SDK version over the last 7 days. Suitable to pass to the execute-sql tool or to display as a copy-paste snippet.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SqlQuery { get; set; }
#nullable restore
#else
        public string SqlQuery { get; set; }
#endif
        /// <summary>Per-version badge tooltip text matching the SDK Doctor UI exactly. Quote verbatim when reporting to users. Varies by state: &apos;Released X ago. Upgrade recommended.&apos; for outdated versions, &apos;You have the latest available. Click Releases above to check for any since.&apos; for current versions, or &apos;Released X ago. Upgrading is a good idea, but it&apos;s not urgent yet.&apos; for recent-but-behind versions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusReason { get; set; }
#nullable restore
#else
        public string StatusReason { get; set; }
#endif
        /// <summary>In-use SDK version string, e.g. &apos;1.298.0&apos;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Version { get; set; }
#nullable restore
#else
        public string Version { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Models.SdkReleaseAssessment"/> and sets the default values.
        /// </summary>
        public SdkReleaseAssessment()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.SdkReleaseAssessment"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PostHog.OpenApiClient.Models.SdkReleaseAssessment CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PostHog.OpenApiClient.Models.SdkReleaseAssessment();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activity_page_url", n => { ActivityPageUrl = n.GetStringValue(); } },
                { "count", n => { Count = n.GetIntValue(); } },
                { "days_since_release", n => { DaysSinceRelease = n.GetIntValue(); } },
                { "is_current_or_newer", n => { IsCurrentOrNewer = n.GetBoolValue(); } },
                { "is_old", n => { IsOld = n.GetBoolValue(); } },
                { "is_outdated", n => { IsOutdated = n.GetBoolValue(); } },
                { "max_timestamp", n => { MaxTimestamp = n.GetStringValue(); } },
                { "needs_updating", n => { NeedsUpdating = n.GetBoolValue(); } },
                { "release_date", n => { ReleaseDate = n.GetStringValue(); } },
                { "released_ago", n => { ReleasedAgo = n.GetStringValue(); } },
                { "sql_query", n => { SqlQuery = n.GetStringValue(); } },
                { "status_reason", n => { StatusReason = n.GetStringValue(); } },
                { "version", n => { Version = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("activity_page_url", ActivityPageUrl);
            writer.WriteIntValue("count", Count);
            writer.WriteIntValue("days_since_release", DaysSinceRelease);
            writer.WriteBoolValue("is_current_or_newer", IsCurrentOrNewer);
            writer.WriteBoolValue("is_old", IsOld);
            writer.WriteBoolValue("is_outdated", IsOutdated);
            writer.WriteStringValue("max_timestamp", MaxTimestamp);
            writer.WriteBoolValue("needs_updating", NeedsUpdating);
            writer.WriteStringValue("released_ago", ReleasedAgo);
            writer.WriteStringValue("release_date", ReleaseDate);
            writer.WriteStringValue("sql_query", SqlQuery);
            writer.WriteStringValue("status_reason", StatusReason);
            writer.WriteStringValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
