// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    /// <summary>* `user` - user* `repo` - repo* `marketplace` - marketplace* `codex` - codex</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SkillSourceEnum
    {
        [EnumMember(Value = "user")]
        #pragma warning disable CS1591
        User,
        #pragma warning restore CS1591
        [EnumMember(Value = "repo")]
        #pragma warning disable CS1591
        Repo,
        #pragma warning restore CS1591
        [EnumMember(Value = "marketplace")]
        #pragma warning disable CS1591
        Marketplace,
        #pragma warning restore CS1591
        [EnumMember(Value = "codex")]
        #pragma warning disable CS1591
        Codex,
        #pragma warning restore CS1591
    }
}
