// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    /// <summary>* `default` - default* `acceptEdits` - acceptEdits* `plan` - plan* `bypassPermissions` - bypassPermissions* `auto` - auto* `read-only` - read-only* `full-access` - full-access</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TaskRunBootstrapCreateRequestInitialPermissionModeEnum
    {
        [EnumMember(Value = "default")]
        #pragma warning disable CS1591
        Default,
        #pragma warning restore CS1591
        [EnumMember(Value = "acceptEdits")]
        #pragma warning disable CS1591
        AcceptEdits,
        #pragma warning restore CS1591
        [EnumMember(Value = "plan")]
        #pragma warning disable CS1591
        Plan,
        #pragma warning restore CS1591
        [EnumMember(Value = "bypassPermissions")]
        #pragma warning disable CS1591
        BypassPermissions,
        #pragma warning restore CS1591
        [EnumMember(Value = "auto")]
        #pragma warning disable CS1591
        Auto,
        #pragma warning restore CS1591
        [EnumMember(Value = "read-only")]
        #pragma warning disable CS1591
        ReadOnly,
        #pragma warning restore CS1591
        [EnumMember(Value = "full-access")]
        #pragma warning disable CS1591
        FullAccess,
        #pragma warning restore CS1591
    }
}
