// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    /// <summary>* `interactive` - interactive* `background` - background</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TaskExecutionModeEnum
    {
        [EnumMember(Value = "interactive")]
        #pragma warning disable CS1591
        Interactive,
        #pragma warning restore CS1591
        [EnumMember(Value = "background")]
        #pragma warning disable CS1591
        Background,
        #pragma warning restore CS1591
    }
}
