// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    /// <summary>* `plan` - plan* `context` - context* `reference` - reference* `output` - output* `artifact` - artifact* `tree_snapshot` - tree_snapshot* `user_attachment` - user_attachment</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TaskRunArtifactTypeEnum
    {
        [EnumMember(Value = "plan")]
        #pragma warning disable CS1591
        Plan,
        #pragma warning restore CS1591
        [EnumMember(Value = "context")]
        #pragma warning disable CS1591
        Context,
        #pragma warning restore CS1591
        [EnumMember(Value = "reference")]
        #pragma warning disable CS1591
        Reference,
        #pragma warning restore CS1591
        [EnumMember(Value = "output")]
        #pragma warning disable CS1591
        Output,
        #pragma warning restore CS1591
        [EnumMember(Value = "artifact")]
        #pragma warning disable CS1591
        Artifact,
        #pragma warning restore CS1591
        [EnumMember(Value = "tree_snapshot")]
        #pragma warning disable CS1591
        Tree_snapshot,
        #pragma warning restore CS1591
        [EnumMember(Value = "user_attachment")]
        #pragma warning disable CS1591
        User_attachment,
        #pragma warning restore CS1591
    }
}
