// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TaskCommentEntry : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Normalized text or document anchor.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.TaskCommentEntryAnchor? Anchor { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.TaskCommentEntryAnchor Anchor { get; set; }
#endif
        /// <summary>Comment author&apos;s display name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Author { get; set; }
#nullable restore
#else
        public string Author { get; set; }
#endif
        /// <summary>Canvas version receiving the comment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CanvasVersionId { get; set; }
#nullable restore
#else
        public string CanvasVersionId { get; set; }
#endif
        /// <summary>Byte-bounded comment body chunk.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Content { get; set; }
#nullable restore
#else
        public string Content { get; set; }
#endif
        /// <summary>Byte offset for the next body chunk, or null when complete.</summary>
        public int? ContentNextOffset { get; set; }
        /// <summary>Whether this comment body has more content.</summary>
        public bool? ContentTruncated { get; set; }
        /// <summary>When the comment was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Comment id.</summary>
        public Guid? Id { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Models.TaskCommentEntry"/> and sets the default values.
        /// </summary>
        public TaskCommentEntry()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.TaskCommentEntry"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PostHog.OpenApiClient.Models.TaskCommentEntry CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PostHog.OpenApiClient.Models.TaskCommentEntry();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "anchor", n => { Anchor = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.TaskCommentEntryAnchor>(global::Soenneker.PostHog.OpenApiClient.Models.TaskCommentEntryAnchor.CreateFromDiscriminatorValue); } },
                { "author", n => { Author = n.GetStringValue(); } },
                { "canvas_version_id", n => { CanvasVersionId = n.GetStringValue(); } },
                { "content", n => { Content = n.GetStringValue(); } },
                { "content_next_offset", n => { ContentNextOffset = n.GetIntValue(); } },
                { "content_truncated", n => { ContentTruncated = n.GetBoolValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.TaskCommentEntryAnchor>("anchor", Anchor);
            writer.WriteStringValue("author", Author);
            writer.WriteStringValue("canvas_version_id", CanvasVersionId);
            writer.WriteStringValue("content", Content);
            writer.WriteIntValue("content_next_offset", ContentNextOffset);
            writer.WriteBoolValue("content_truncated", ContentTruncated);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteGuidValue("id", Id);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
