// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    /// <summary>
    /// Why this observation made the feed.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WatchFeedItemReason : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Highest-priority rule the observation satisfied: `signal_emitted` (it pushed a signal), `unusual_verdict` (a monitor answer that is the minority for that scanner this window), `verdict_yes` (a monitor hit, when the window is too thin to know which answer is unusual), `outlier_score` (far from the scanner&apos;s window average), `rare_tag` (a tag uncommon for the scanner this window), `novel_summary` (a summary that reads unlike the scanner&apos;s other sessions this window), `notable` (the scan itself judged the session worth watching), `friction` (the scan describes errors, retries, or dead ends), `unviewed_recent` (new to you), `recent` (nothing special, newest available).* `signal_emitted` - Signal Emitted* `unusual_verdict` - Unusual Verdict* `notable` - Notable* `verdict_yes` - Verdict Yes* `outlier_score` - Outlier Score* `rare_tag` - Rare Tag* `novel_summary` - Novel Summary* `friction` - Friction* `unviewed_recent` - Unviewed Recent* `recent` - Recent</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.WatchFeedReasonKind? Kind { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.WatchFeedReasonKind Kind { get; set; }
#endif
        /// <summary>The scan&apos;s own 0-1 judgment of how much a team would benefit from watching, for `notable`.</summary>
        public double? Notability { get; set; }
        /// <summary>The scan&apos;s own sentence naming why the session is worth watching. Present only on the `notable` reason kind, and preferred over copy derived from the reason kind. Absent on observations scanned before notability shipped.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NotabilityReason { get; set; }
#nullable restore
#else
        public string NotabilityReason { get; set; }
#endif
        /// <summary>The observation&apos;s score, for `outlier_score`.</summary>
        public double? Score { get; set; }
        /// <summary>Signals this observation emitted, for `signal_emitted`.</summary>
        public int? SignalsCount { get; set; }
        /// <summary>The rare tag that ranked the observation, for `rare_tag`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Tag { get; set; }
#nullable restore
#else
        public string Tag { get; set; }
#endif
        /// <summary>Share (0-1) of the scanner&apos;s window observations carrying `tag`, for `rare_tag`.</summary>
        public double? TagShare { get; set; }
        /// <summary>The monitor&apos;s answer, for `unusual_verdict`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Verdict { get; set; }
#nullable restore
#else
        public string Verdict { get; set; }
#endif
        /// <summary>Share (0-1) of the scanner&apos;s window observations with this answer, for `unusual_verdict`.</summary>
        public double? VerdictShare { get; set; }
        /// <summary>The scanner&apos;s mean score in the window, for `outlier_score`.</summary>
        public double? WindowMean { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Models.WatchFeedItemReason"/> and sets the default values.
        /// </summary>
        public WatchFeedItemReason()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.WatchFeedItemReason"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PostHog.OpenApiClient.Models.WatchFeedItemReason CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PostHog.OpenApiClient.Models.WatchFeedItemReason();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "kind", n => { Kind = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.WatchFeedReasonKind>(global::Soenneker.PostHog.OpenApiClient.Models.WatchFeedReasonKind.CreateFromDiscriminatorValue); } },
                { "notability", n => { Notability = n.GetDoubleValue(); } },
                { "notability_reason", n => { NotabilityReason = n.GetStringValue(); } },
                { "score", n => { Score = n.GetDoubleValue(); } },
                { "signals_count", n => { SignalsCount = n.GetIntValue(); } },
                { "tag", n => { Tag = n.GetStringValue(); } },
                { "tag_share", n => { TagShare = n.GetDoubleValue(); } },
                { "verdict", n => { Verdict = n.GetStringValue(); } },
                { "verdict_share", n => { VerdictShare = n.GetDoubleValue(); } },
                { "window_mean", n => { WindowMean = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.WatchFeedReasonKind>("kind", Kind);
            writer.WriteDoubleValue("notability", Notability);
            writer.WriteStringValue("notability_reason", NotabilityReason);
            writer.WriteDoubleValue("score", Score);
            writer.WriteIntValue("signals_count", SignalsCount);
            writer.WriteStringValue("tag", Tag);
            writer.WriteDoubleValue("tag_share", TagShare);
            writer.WriteStringValue("verdict", Verdict);
            writer.WriteDoubleValue("verdict_share", VerdictShare);
            writer.WriteDoubleValue("window_mean", WindowMean);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
