// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    /// <summary>
    /// &quot;Output: serialises a WizardSessionDTO returned by the facade.&quot;
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WizardSessionDto : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The created_at property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The user who initiated this wizard run (null for runs created before attribution existed). Lets the UI name whose run it is.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.WizardSessionDtoCreatedBy? CreatedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.WizardSessionDtoCreatedBy CreatedBy { get; set; }
#endif
        /// <summary>The error property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.WizardSessionDtoError? Error { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.WizardSessionDtoError Error { get; set; }
#endif
        /// <summary>The event_plan property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.WizardSessionDtoEventPlan? EventPlan { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.WizardSessionDtoEventPlan EventPlan { get; set; }
#endif
        /// <summary>Markdown handoff doc the wizard produced for this run (its setup report), or null while the run hasn&apos;t written one. Sticky once set.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HandoffText { get; set; }
#nullable restore
#else
        public string HandoffText { get; set; }
#endif
        /// <summary>The is_stale property</summary>
        public bool? IsStale { get; set; }
        /// <summary>The question the wizard is currently blocked on, or null when nothing is pending.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PostHog.OpenApiClient.Models.WizardSessionDtoPendingInput? PendingInput { get; set; }
#nullable restore
#else
        public global::Soenneker.PostHog.OpenApiClient.Models.WizardSessionDtoPendingInput PendingInput { get; set; }
#endif
        /// <summary>* `idle` - IDLE* `running` - RUNNING* `completed` - COMPLETED* `error` - ERROR</summary>
        public global::Soenneker.PostHog.OpenApiClient.Models.RunPhaseEnum? RunPhase { get; set; }
        /// <summary>The session_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SessionId { get; set; }
#nullable restore
#else
        public string SessionId { get; set; }
#endif
        /// <summary>The skill_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SkillId { get; set; }
#nullable restore
#else
        public string SkillId { get; set; }
#endif
        /// <summary>The started_at property</summary>
        public DateTimeOffset? StartedAt { get; set; }
        /// <summary>The tasks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PostHog.OpenApiClient.Models.WizardTaskDto>? Tasks { get; set; }
#nullable restore
#else
        public List<global::Soenneker.PostHog.OpenApiClient.Models.WizardTaskDto> Tasks { get; set; }
#endif
        /// <summary>The team_id property</summary>
        public int? TeamId { get; set; }
        /// <summary>The updated_at property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The workflow_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkflowId { get; set; }
#nullable restore
#else
        public string WorkflowId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Models.WizardSessionDto"/> and sets the default values.
        /// </summary>
        public WizardSessionDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.WizardSessionDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PostHog.OpenApiClient.Models.WizardSessionDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PostHog.OpenApiClient.Models.WizardSessionDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "created_by", n => { CreatedBy = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.WizardSessionDtoCreatedBy>(global::Soenneker.PostHog.OpenApiClient.Models.WizardSessionDtoCreatedBy.CreateFromDiscriminatorValue); } },
                { "error", n => { Error = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.WizardSessionDtoError>(global::Soenneker.PostHog.OpenApiClient.Models.WizardSessionDtoError.CreateFromDiscriminatorValue); } },
                { "event_plan", n => { EventPlan = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.WizardSessionDtoEventPlan>(global::Soenneker.PostHog.OpenApiClient.Models.WizardSessionDtoEventPlan.CreateFromDiscriminatorValue); } },
                { "handoff_text", n => { HandoffText = n.GetStringValue(); } },
                { "is_stale", n => { IsStale = n.GetBoolValue(); } },
                { "pending_input", n => { PendingInput = n.GetObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.WizardSessionDtoPendingInput>(global::Soenneker.PostHog.OpenApiClient.Models.WizardSessionDtoPendingInput.CreateFromDiscriminatorValue); } },
                { "run_phase", n => { RunPhase = n.GetEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.RunPhaseEnum>(); } },
                { "session_id", n => { SessionId = n.GetStringValue(); } },
                { "skill_id", n => { SkillId = n.GetStringValue(); } },
                { "started_at", n => { StartedAt = n.GetDateTimeOffsetValue(); } },
                { "tasks", n => { Tasks = n.GetCollectionOfObjectValues<global::Soenneker.PostHog.OpenApiClient.Models.WizardTaskDto>(global::Soenneker.PostHog.OpenApiClient.Models.WizardTaskDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "team_id", n => { TeamId = n.GetIntValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "workflow_id", n => { WorkflowId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.WizardSessionDtoCreatedBy>("created_by", CreatedBy);
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.WizardSessionDtoError>("error", Error);
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.WizardSessionDtoEventPlan>("event_plan", EventPlan);
            writer.WriteStringValue("handoff_text", HandoffText);
            writer.WriteBoolValue("is_stale", IsStale);
            writer.WriteObjectValue<global::Soenneker.PostHog.OpenApiClient.Models.WizardSessionDtoPendingInput>("pending_input", PendingInput);
            writer.WriteEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.RunPhaseEnum>("run_phase", RunPhase);
            writer.WriteStringValue("session_id", SessionId);
            writer.WriteStringValue("skill_id", SkillId);
            writer.WriteDateTimeOffsetValue("started_at", StartedAt);
            writer.WriteCollectionOfObjectValues<global::Soenneker.PostHog.OpenApiClient.Models.WizardTaskDto>("tasks", Tasks);
            writer.WriteIntValue("team_id", TeamId);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteStringValue("workflow_id", WorkflowId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
