// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PostHog.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class YAxisSettings : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The scale property</summary>
        public global::Soenneker.PostHog.OpenApiClient.Models.Scale? Scale { get; set; }
        /// <summary>The showGridLines property</summary>
        public bool? ShowGridLines { get; set; }
        /// <summary>The showTicks property</summary>
        public bool? ShowTicks { get; set; }
        /// <summary>Whether the Y axis should start at zero</summary>
        public bool? StartAtZero { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.YAxisSettings"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PostHog.OpenApiClient.Models.YAxisSettings CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PostHog.OpenApiClient.Models.YAxisSettings();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "scale", n => { Scale = n.GetEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.Scale>(); } },
                { "showGridLines", n => { ShowGridLines = n.GetBoolValue(); } },
                { "showTicks", n => { ShowTicks = n.GetBoolValue(); } },
                { "startAtZero", n => { StartAtZero = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.PostHog.OpenApiClient.Models.Scale>("scale", Scale);
            writer.WriteBoolValue("showGridLines", ShowGridLines);
            writer.WriteBoolValue("showTicks", ShowTicks);
            writer.WriteBoolValue("startAtZero", StartAtZero);
        }
    }
}
#pragma warning restore CS0618
