// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.PostHog.OpenApiClient.Api.Environments.Item.Integrations.Item.Clickup_workspaces
{
    /// <summary>
    /// Builds and executes requests for operations under \api\environments\{environment_-id}\integrations\{id}\clickup_workspaces
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Clickup_workspacesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The EmptyPathSegment property</summary>
        public global::Soenneker.PostHog.OpenApiClient.Api.Environments.Item.Integrations.Item.Clickup_workspaces.EmptyPathSegmentRequestBuilder EmptyPathSegment
        {
            get => new global::Soenneker.PostHog.OpenApiClient.Api.Environments.Item.Integrations.Item.Clickup_workspaces.EmptyPathSegmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Api.Environments.Item.Integrations.Item.Clickup_workspaces.Clickup_workspacesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Clickup_workspacesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/environments/{environment_%2Did}/integrations/{id}/clickup_workspaces", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Api.Environments.Item.Integrations.Item.Clickup_workspaces.Clickup_workspacesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Clickup_workspacesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/environments/{environment_%2Did}/integrations/{id}/clickup_workspaces", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
