// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.PostHog.OpenApiClient.Api.Environments.Item.Error_tracking.Recommendations.Item;
using Soenneker.PostHog.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.PostHog.OpenApiClient.Api.Environments.Item.Error_tracking.Recommendations
{
    /// <summary>
    /// Builds and executes requests for operations under \api\environments\{project_id}\error_tracking\recommendations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RecommendationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.PostHog.OpenApiClient.api.environments.item.error_tracking.recommendations.item collection</summary>
        /// <param name="position">A UUID string identifying this error tracking recommendation.</param>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Api.Environments.Item.Error_tracking.Recommendations.Item.RecommendationsItemRequestBuilder"/></returns>
        public global::Soenneker.PostHog.OpenApiClient.Api.Environments.Item.Error_tracking.Recommendations.Item.RecommendationsItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.PostHog.OpenApiClient.Api.Environments.Item.Error_tracking.Recommendations.Item.RecommendationsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Api.Environments.Item.Error_tracking.Recommendations.RecommendationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RecommendationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/environments/{project_id}/error_tracking/recommendations{?limit*,offset*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Api.Environments.Item.Error_tracking.Recommendations.RecommendationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RecommendationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/environments/{project_id}/error_tracking/recommendations{?limit*,offset*}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.PaginatedErrorTrackingRecommendationList"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.PostHog.OpenApiClient.Models.PaginatedErrorTrackingRecommendationList?> GetAsync(Action<RequestConfiguration<global::Soenneker.PostHog.OpenApiClient.Api.Environments.Item.Error_tracking.Recommendations.RecommendationsRequestBuilder.RecommendationsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.PostHog.OpenApiClient.Models.PaginatedErrorTrackingRecommendationList> GetAsync(Action<RequestConfiguration<global::Soenneker.PostHog.OpenApiClient.Api.Environments.Item.Error_tracking.Recommendations.RecommendationsRequestBuilder.RecommendationsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.PostHog.OpenApiClient.Models.PaginatedErrorTrackingRecommendationList>(requestInfo, global::Soenneker.PostHog.OpenApiClient.Models.PaginatedErrorTrackingRecommendationList.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.PostHog.OpenApiClient.Api.Environments.Item.Error_tracking.Recommendations.RecommendationsRequestBuilder.RecommendationsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.PostHog.OpenApiClient.Api.Environments.Item.Error_tracking.Recommendations.RecommendationsRequestBuilder.RecommendationsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Api.Environments.Item.Error_tracking.Recommendations.RecommendationsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.PostHog.OpenApiClient.Api.Environments.Item.Error_tracking.Recommendations.RecommendationsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.PostHog.OpenApiClient.Api.Environments.Item.Error_tracking.Recommendations.RecommendationsRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class RecommendationsRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            /// <summary>Number of results to return per page.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>The initial index from which to return the results.</summary>
            [QueryParameter("offset")]
            public int? Offset { get; set; }
        }
    }
}
#pragma warning restore CS0618
