// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.PostHog.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Mcp_gateway.Servers.Item.Tools
{
    /// <summary>
    /// Builds and executes requests for operations under \api\projects\{projectId}\mcp_gateway\servers\{id}\tools
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ToolsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Mcp_gateway.Servers.Item.Tools.ToolsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ToolsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/projects/{projectId}/mcp_gateway/servers/{id}/tools{?scope_service_account_id*,scope_type*,scope_user_id*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Mcp_gateway.Servers.Item.Tools.ToolsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ToolsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/projects/{projectId}/mcp_gateway/servers/{id}/tools{?scope_service_account_id*,scope_type*,scope_user_id*}", rawUrl)
        {
        }
        /// <summary>
        /// Tool catalog with the resolved policy for a scope.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Models.PaginatedResolvedToolPolicyList"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.PostHog.OpenApiClient.Models.PaginatedResolvedToolPolicyList?> GetAsync(Action<RequestConfiguration<global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Mcp_gateway.Servers.Item.Tools.ToolsRequestBuilder.ToolsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.PostHog.OpenApiClient.Models.PaginatedResolvedToolPolicyList> GetAsync(Action<RequestConfiguration<global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Mcp_gateway.Servers.Item.Tools.ToolsRequestBuilder.ToolsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.PostHog.OpenApiClient.Models.PaginatedResolvedToolPolicyList>(requestInfo, global::Soenneker.PostHog.OpenApiClient.Models.PaginatedResolvedToolPolicyList.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Tool catalog with the resolved policy for a scope.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Mcp_gateway.Servers.Item.Tools.ToolsRequestBuilder.ToolsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Mcp_gateway.Servers.Item.Tools.ToolsRequestBuilder.ToolsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Mcp_gateway.Servers.Item.Tools.ToolsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Mcp_gateway.Servers.Item.Tools.ToolsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Mcp_gateway.Servers.Item.Tools.ToolsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Tool catalog with the resolved policy for a scope.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ToolsRequestBuilderGetQueryParameters 
        {
            /// <summary>Agent scope target. Required when scope_type is agent.</summary>
            [QueryParameter("scope_service_account_id")]
            public Guid? ScopeServiceAccountId { get; set; }
            /// <summary>&quot;Which scope to resolve: the team default, one member, or one agent.* `team` - Team default* `member` - Member* `agent` - Agent&quot;</summary>
            [QueryParameter("scope_type")]
            public global::Soenneker.PostHog.OpenApiClient.Models.McpGatewayServersToolsRetrieveScopeTypeParameter? ScopeType { get; set; }
            /// <summary>Member scope target. Defaults to the requesting user.</summary>
            [QueryParameter("scope_user_id")]
            public int? ScopeUserId { get; set; }
        }
    }
}
#pragma warning restore CS0618
