// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Sandbox_environments.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Sandbox_environments
{
    /// <summary>
    /// Builds and executes requests for operations under \api\projects\{project_id}\sandbox_environments
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Sandbox_environmentsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The EmptyPathSegment property</summary>
        public global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Sandbox_environments.EmptyPathSegmentRequestBuilder EmptyPathSegment
        {
            get => new global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Sandbox_environments.EmptyPathSegmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.PostHog.OpenApiClient.api.projects.item.sandbox_environments.item collection</summary>
        /// <param name="position">A UUID string identifying this sandbox environment.</param>
        /// <returns>A <see cref="global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Sandbox_environments.Item.Sandbox_environmentsItemRequestBuilder"/></returns>
        public global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Sandbox_environments.Item.Sandbox_environmentsItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Sandbox_environments.Item.Sandbox_environmentsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Sandbox_environments.Sandbox_environmentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Sandbox_environmentsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/projects/{project_id}/sandbox_environments", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PostHog.OpenApiClient.Api.Projects.Item.Sandbox_environments.Sandbox_environmentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Sandbox_environmentsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/projects/{project_id}/sandbox_environments", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
